### ISSUE TITLE
Integration / replicated.sql placement

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#101]
@doolse - Do you know the purpose for https://github.com/equella/Equella/blob/master/Source/Integration/replicated.sql  ?  

Looks like a template to setup a Replicated Data Source for user auth in Equella.  If so, I think this should move over to the docs repo for user auth.  Do you agree?

**Comment by doolse** [comment]
Yeah it looks like a RDS init script. So yeah it's better off in the documentation.

**Comment by cbeach47** [comment]
Moved to https://github.com/equella/equella.github.io/blob/master/example-scripts/replicated.sql
