### ISSUE TITLE
Remove OfficeIntegration from core Equella source

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#102]
The OfficeIntegration code has been moved over to the [equella-office-integration](https://github.com/equella/equella-office-integration) repo.  However, there is still a copy in https://github.com/equella/Equella/tree/master/Source/Integration/office-integration .  Need to remove the copy, especially since there are DLLs that has licensing concerns (handled via #98)

**Comment by abidingotter** [comment]
I think it used to be a submodule, but is now has a copy in the actual repo because submodules were removed as part of the migration.

**Comment by cbeach47** [comment]
Pull request #103 opened.
