### ISSUE TITLE
Choose a Foss License

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#11]
- [x]  Review Prior Research on the License

- [x]  Choose a FOSS License (Likely Apache2  - need to be validated

- [x]  Document and communicate the choice

- [x]  Confirm decision with Key Stakeholders  Edalex/Unicon Exec

**Comment by bjagg** [comment]
This is related to #4 in that a Gradle plugin has been found for NOTICE file generation, but it is Apache 2 specific

**Comment by bjagg** [comment]
Apache2 is the license Apereo recommends. During our call with Edalex on 4/19/2017, we proposed this as the candidate license for Equalla. Edalex and Unicon approved.
