### ISSUE TITLE
Ensure all file uploads are done using AJAX

### ISSUE THREAD

**Issue by doolse** [equella/Equella#110]
Progress bars only work with AJAX file uploads, so any multipart uploads need to be converted over to AJAX.

**Comment by cbeach47** [comment]
As per Jolse:  all file uploads still work but you only get progress bars for controls which use the AJAX functionality

This is a lower priority issue.

**Comment by emcgarrahan** [comment]
Chris to get an update from Edalex. If this won't be completed very soon, it should go in Roadmap milestone.
