### ISSUE TITLE
Scheduled Tasks: Run at funny times

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#174]
Some scheduled tasks start at all sorts of funny times, regardless of Settings.
 e.g. My installation has two institutions, both with DailyTasks set to run at 11pm, but they don't.
 Usually they run at about 8:30am, which is about the time I unlock the pc.
 But one morning they ran at 05:50am, when I was not even awake.
 
 Note: These are Daily Tasks, not Hourly. e.g. Clean-Thumbnail-queue."

Issue Converted from original Equella JIRA

**Comment by cbeach47** [comment]
I've reviewed several runs of scheduled tasks across different institution, and they all have followed:  https://github.com/equella/equella.github.io/blob/master/guides/ScheduledTasksGuide.md .  Closing this ticket.  Please reopen with a specific example if the scheduled tasks are not respecting the run times.
