### ISSUE TITLE
Review the existing the Automated Tests

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#20]
- [ ] Review the existing automated tests

- [ ]  Determine next steps for the automated tests

- [ ]    Copy the Automated Tests into an Equella Repo   (Jolse has the repo to move over)

**Comment by emcgarrahan** [comment]
These exist in the Equella auto-test repo however Jolse had been trying to work on these and has more recent data.

**Comment by msultzaberger** [comment]
Regarding the core Equella project, I found that there is a common-ant.xml file that controls whether or not the junit tests are run for each project.  The common-ant.xml file will run all tests in the test folder and report the results in the test.reports folder.  Attached is a list of the Projects and testcases that are currently being executed during the ant release command.

[20170508 Ant Release Testcases.txt](https://github.com/equella/Equella/files/984692/20170508.Ant.Release.Testcases.txt)

**Comment by msultzaberger** [comment]
I reviewed the automated tests project and believe that there is a high value in keeping this project as part of the Equella open sourcing.  I've not been able to build and run the project locally; however, I reviewed the tests and feel that it covers a significant amount of the Equella code.

**Comment by msultzaberger** [comment]
Next steps is to create/find the documentation, move the code to the Equella GitHub repository and determine if there are any outstanding issues and resolve them.  At this point, this should most likely be considered a "nice to have" and we should not be spending roadmap hours on it other than getting the code into GitHub.

**Comment by doolse** [comment]
The selenium tests are now in a repo - https://github.com/equella/equella-autotests
