### ISSUE TITLE
Remove the in-app documentation

### ISSUE THREAD

**Issue by doolse** [equella/Equella#25]
Currently there is a page in EQUELLA which is built by downloading doco from maestro.equella.com. I suspect we just want to get rid of this as the doco will be accessible from github.

So the places in which doco needs to be removed:

- Downloads tab (server administrator)
  - IntegrationDownloadTab.java
  - The "integrationDownloadSection" extension point and anything that extends it
- REST API docs
  - swagger.ftl

For now just removing it is ok, eventually we probably want to put back in a link somewhere to github docs (perhaps based on a tag if our docs are versioned)

**Comment by drewwills** [comment]
Sounds very reasonable.

**Comment by abidingotter** [comment]
Also in the "Integration Pack" (the code samples etc)

**Comment by ddelblanco** [comment]
I've removed the tab and all that was generating it... but I don't know if I should go beyond and touch something in the /com.tle.integration.standard project... or just leave it there.

**Comment by ddelblanco** [comment]
As the code has been merged, I close this one. We can reopen if something more arises.
