### ISSUE TITLE
Swagger caching base URL

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#250]
When viewing the apidocs.do page for a particular institution then changing to another institution Swagger is caching the base path from the first institution causing the Swagger page to request information from the first institution. EPS had similar issues and ended up devising a solution to do away with the base path. We should perhaps look at doing something similar although some quick tests showed that it wasn't just a drop in solution.		

COMMENTS FROM THE ORIGINAL JIRA:
;Here's a related sub-bug, possibly only occurring in IE(?). 
 Make sure you have EDIT_USER_MANAGEMENT.
 Go to apidocs.do
 Do a GET on Role1 (by uuid or name).
 It works. 
 
 Revoke EDIT_USER_MANAGEMENT
 Log out and in.
 Do the same GET on Role1.
 It still returns the details of Role1.(naughty!)
 Do the same GET on some other role.
 It returns a 403. (good)
--------------------------------
This may be fixed by recent upgrades to swagger?
-----------------------------
No, it isn't, but I suppose it's being cached as it's told to. So maybe it's not a bug as such...

**Comment by cbeach47** [comment]
This is covered by https://github.com/equella/Equella/issues/423 .   Closing.
