### ISSUE TITLE
Create a "Golden Ticket" Equella license and share it publicly

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#26]
This is an Equella license key that...
  - Is valid for any installation
  - Doesn't expire

**Comment by emcgarrahan** [comment]
Use case: clients that don't want to stop running the build they have.

**Comment by doolse** [comment]
The license key which works for any host and works until 2100 is here:
https://github.com/equella/Equella/wiki/License-key-for-existing-installations
Feel free to move it elsewhere

**Comment by ict-els** [comment]
Hi @doolse / @drewwills 
We have an old version (6.3) of Equella and as of yesterday is advising that our license has expired and is therefore inaccessible.
Do you know where that license key wiki page is kept now? As for me just forwards to https://github.com/equella/Equella/wiki
Thanks,
Scott
ps you've done a great job doing all you have!

**Comment by atpurcell** [comment]
Hi @doolse 

That license key would be really useful but the link you provided doesn't work. Can you put the license key somewhere I can grab it?
