### ISSUE TITLE
Support for the `Strict-Transport-Security` header

### ISSUE THREAD

**Issue by doolse** [equella/Equella#261]
EQUELLA installs which should only be accessible by HTTPS can make the browser enforce this by using the `Strict-Transport-Security` header. This can be a server level config setting in `optional-config.properties`

https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet

Enable with:
```
strictTransportSecurity.maxage = 86400 # length in seconds
```

**Comment by mrblippy** [comment]
Closing, manual testing was successful
