### ISSUE TITLE
Shuffle list control doesn't work when you enter pipe or percent characters.

### ISSUE THREAD

**Issue by abidingotter** [equella/Equella#269]
When you implement a shuffle list, and the user enters either the pipe or percent ( | % ) symbols in the shuffle list AND you also have visibility scripting on that page:

the | symbol triggers java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
the % symbol triggers java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern

when the visibility script activates.

Here is a video showing the behaviour:

https://ilos.video/87PaI1

**Comment by abidingotter** [comment]
As noted in the pull request:

**Comment by mrblippy** [comment]
Fixed: verified with manual testing
