### ISSUE TITLE
Task list broken in blackboard resource centre module

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#279]
tested in blackboard Release 9.1.201510.1175205

Steps to replicate:

- Add the equella Resource Centre Module to your blackboard home screen (go to MyInstitution and click the AddModule button)

-  The following error is produced when it tries to load the workflow task list

![task error](https://user-images.githubusercontent.com/4625498/28655605-494e78fe-72e0-11e7-952c-ed3adfeaf047.PNG)

**Comment by doolse** [comment]
Wasn't broken, just needed an externally accessible EQUELLA
