### ISSUE TITLE
Expose "EXISTS" operator in Manage Resources queries

### ISSUE THREAD

**Issue by phette23** [equella/Equella#287]
If you use the **Edit query** button on the Manage Resources (itemadmin.do) page, there's no way to query for items where a certain element merely exists. You have to enter in a second parameter so it's only possible to check if the element matches a certain pattern (IS, IS NOT, LIKE, >=, etc.). You cannot begin with a wildcard so you can't even hack around this limitation with a `LIKE '%'` query.

However, by editing the `c` parameter (the WHERE clause) of the itemadmin.do URL, you're able to perform EXISTS queries e.g.

/access/itemadmin.do?c=WHERE+%2Fxml%2Felement+EXISTS&in={{uuid}}

the functionality just needs to be exposed in the query editor.

**Comment by cbeach47** [comment]
Taking a look at this now.

**Comment by cbeach47** [comment]
Fix in place as per #428, along with a couple minor changes to that UX.  Closing this ticket.
