### ISSUE TITLE
Ability to be notified of your item going LIVE

### ISSUE THREAD

**Issue by doolse** [equella/Equella#299]
A contributor would like to be notified when an item they created has gone LIVE (via moderation). This should be a checkbox on the User preferences page.

* It should give you a notification when the item goes LIVE (it could still be in moderation)
* It shouldn't give you a notification if there is no workflow

**Comment by doolse** [comment]
![notifymylive](https://user-images.githubusercontent.com/2178038/29952539-60089824-8f0d-11e7-9248-5311648af47e.png)

**Comment by mrblippy** [comment]
Fixed: verified with manual tests
