### ISSUE TITLE
Remove Dependencies on Pearson Libraries

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#3]

**Comment by doolse** [comment]
There is actually only one pearson library which is open source:
http://developer.pearson.com/pearson-scorm-services/getting-started

What's even better is that this functionality was walled off by a License key flag which no one ever requested, so probably could just be removed completely.

**Comment by emcgarrahan** [comment]
https://docs.google.com/spreadsheets/d/1GYyQ2jdw9IKccQDVt-cpcvgJuI5MuCUgOAzCkr4JIYw/edit?usp=sharing

**Comment by drewwills** [comment]
@doolse -- Can you handle removing this dependency/feature?

**Comment by doolse** [comment]
@abidingotter Did most of the deletion here, done!
