### ISSUE TITLE
Extend SBT work to include download capabilities for jar files

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#30]
Discuss making changes to files/dependency structure such that rather than a collection of binaries; jar files would be obtained through an automatic process.

**Comment by drewwills** [comment]
Thanks for getting this ticket in!

**Comment by drewwills** [comment]
Folks -- we have formed the suspicion that -- if we're successful at this item -- we will also be quite close to loading the sources in any IDE without a plugin.

**Comment by bjagg** [comment]
This will be addressed in #44

**Comment by bjagg** [comment]
@doolse will the work for issue #44 include downloading dependencies?

**Comment by doolse** [comment]
Yeah SBT does all the downloading.

**Comment by drewwills** [comment]
Does that mean we've reached the point where dependencies.zip is not required?
