### ISSUE TITLE
Review "Equella License Review" and create appropriate tasks 

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#31]
https://confluence.unicon.net/confluence/display/ProServ/Equella+License+Review

**Comment by bjagg** [comment]
Separate out those that will only require documentation (like Oracle dependencies) and note those that require additional discussion

**Comment by bjagg** [comment]
https://docs.google.com/spreadsheets/d/1GYyQ2jdw9IKccQDVt-cpcvgJuI5MuCUgOAzCkr4JIYw/edit#gid=0

**Comment by bjagg** [comment]
License review details license compatibility. We need to to document the dependencies first.

**Comment by doolse** [comment]
I've added another tab to the spreadsheet which is a dump of the license report from the "sbt-license-report" plugin. This is a list of all the jars required for the server and admin console currently.

**Comment by bjagg** [comment]
Thanks @doolse. I reviewed those entries.
1. Kaltura is not compatible with Apache. Is this required or can this be an optional download?
2. Jaxen license requires display of the notice somewhere in the documentation. Can this be replaced by Xalan XPath support?

**Comment by bjagg** [comment]
com.pearson.pdn.icodeon:icodeon-java-sdk is not open source. We need to discuss how to address this dependency.

**Comment by bjagg** [comment]
There is a customized Pearson HTTPInvoker class. Since it's in the equella package and Spring is Apache Licensed, we should be okay.

**Comment by bjagg** [comment]
JPF is LGPL licensed, which means we can only use it unmodified. If we can eliminate the customizations, we should be good.

**Comment by bjagg** [comment]
We need to remove dhfjava if we do not know it's origin.

**Comment by bjagg** [comment]
@doolse do you have time Tuesday (my Monday) to have a call for these items? I would like to create issues to address the above and any other we come across.

**Comment by doolse** [comment]
Yeah sure, same time as usual should be good, or even 30 mins earlier if you like.

**Comment by bjagg** [comment]
Great, let's go for 30 minutes earlier. I will send you an email with an invite for today.

**Comment by bjagg** [comment]
1. Pearson icodeon-java-sdk not used
2. eBay component relies on eCommerce
3. Jaxen is not directly referenced nor is it a dependency (must be an unnamed dependency dependency)
