### ISSUE TITLE
Move BIRT reporting plugin out of main code and publish to maven

### ISSUE THREAD

**Issue by doolse** [equella/Equella#32]
EQUELLA reports use an embedded BIRT reporting engine which has a BIRT plugin for querying EQUELLA, the source is in the main repo but it isn't built with the product. 
It should live in it's own repo.

**Comment by drewwills** [comment]
Thanks for adding this issue.  Please create the ones you identify.

**Comment by doolse** [comment]
Waiting for #36

**Comment by bjagg** [comment]
https://github.com/equella/equella-reporting-plugin
