### ISSUE TITLE
Using 'next' and 'prev' buttons while moderating gives inconsistent results

### ISSUE THREAD

**Issue by doolse** [equella/Equella#329]
If you go to your task list and click moderate on the first available task and then use 'next' and 'prev' to go between tasks, you won't necessarily get the results in the order that your task list displayed.

It appears to be only when sorting by "priority" which happens to be the default.

**Comment by doolse** [comment]
I've narrowed it down to the `CustomLuceneSortComparator` which is being used to sort "assign to me" results higher

**Comment by mrblippy** [comment]
Fixed: tested with manual tests
