### ISSUE TITLE
Change tasks to workflow order in Reset to task bulk action

### ISSUE THREAD

**Issue by cathfitz** [equella/Equella#330]
In the Reset to task bulk action, change the task dropdown list to be in the order of the workflow

**Comment by abidingotter** [comment]
It is already alpha-sorted...
Do you mean another list?
![sorted](https://user-images.githubusercontent.com/1694589/30575755-4750e812-9d46-11e7-93dd-1e39035b867d.png)

**Comment by doolse** [comment]
I believe Cath meant to sort it in workflow tree order, not alphabetically.

**Comment by abidingotter** [comment]
Hmm, how do you sort a parallel workflow? :)

**Comment by abidingotter** [comment]
PR created

**Comment by mrblippy** [comment]
Fixed: tested with manual testing
