### ISSUE TITLE
Email notifications: clicking workflow attachments doesn't work if you aren't logged in

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#333]
I received the following email notification for a task that had been rejected:

Resource name | Knitting koramns
-- | --
Owner | Internal Demonstration System Administrator (int.demosysadmin)
Rejected task | Redundant Turkeys
Rejection reason | "See me after class.One of the worst things i have ever seen. I quit, sick of this tom foolery" by Internal Demonstration System Administrator (int.demosysadmin)
Rejection attachment | http://charliedesk:8080/vanilla/workflow/message/d4e639b5-9494-4b8b-8a9e-6390ab4e41ad/selma%26%5E%20sandwich.png
Current task | Clean litterbox
Moderate
Due date | 22/09/2017

When clicking the rejection attachment link you have to be logged in already for it to work. If you aren't logged in it should be redirecting you to the equella login screen

**Comment by abidingotter** [comment]
Best workflow and rejection message ever :)

**Comment by mrblippy** [comment]
Fixed
