### ISSUE TITLE
Admin console : Extra attribute in jar manifest required to match security requirements

### ISSUE THREAD

**Issue by doolse** [equella/Equella#344]
https://www.java.com/en/download/help/trusted_signed_variations.xml

https://www.java.com/en/download/help/java_blocked.xml

Specifically we are getting the `"Your security settings have blocked an application from running due to missing a 'Permissions' manifest attribute in the main jar"` error

**Comment by mrblippy** [comment]
Fixed

**Comment by mrblippy** [comment]
Fixed
