### ISSUE TITLE
Workflow script task: ui changes

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#347]
Two issues here:
* Script tasks don't appear in the 'Filter by workflow tasks' dropdown in My Resources, My Tasks and Manage Tasks pages
* When an item is stuck at a failing script task The moderation progress table doesn't have a corresponding entry
![progress](https://user-images.githubusercontent.com/4625498/31257412-217a20ae-aa84-11e7-8fc0-3de866570b01.PNG)

**Comment by abidingotter** [comment]
1. Script tasks now appear in the filter dropdown in Manage Resources, but NOT in My Tasks (it could never be *your* task)
2. This is more difficult than it might appear.  There is code all over the place looking at the status and expecting only WorkflowItemStatus objects, not ScriptStatus ones.  Besides, this is a list of the current moderators, which there are none, so does it even make sense?

**Comment by mrblippy** [comment]
Shouldn't failed script tasks show on the managetasks.do? Because at the moment they aren't

**Comment by abidingotter** [comment]
@mrblippy  They appear under Manage Resources.  They aren't under Manage Tasks because it isn't a task.

**Comment by mrblippy** [comment]
Fixed: script tasks can now be filtered successfully from the manage resources page
