### ISSUE TITLE
File manager applet and attachment control not playing nicely together

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#348]
Attachments are getting doubled up when an attachment control and file manager are both present in a contribution wizard.

Steps to reproduce:
*  Setup a contribution wizard that contains a file manager and file attachment control on the same page.
* Add an attachment to the file attachment control
* In the file manager section you will see the attachment you added in the last step appear twice (similar to the screenshot below). When the item gets saved it appears there is only one copy of the attachment in the filestore, but it displays twice.
![double attach](https://user-images.githubusercontent.com/4625498/31264002-e3092e2c-aab1-11e7-9dcb-c588f31582bd.PNG)

**Comment by doolse** [comment]
It's because the filemanager has a "select top level attachments" checkbox which is checked. Unfortunately it's doing what it's supposed to.
