### ISSUE TITLE
Determine how to build Equella keystore

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#35]

**Comment by bjagg** [comment]
Emailed Jolse for details on the use of this keystore

**Comment by ddelblanco** [comment]
We have been researching and we propose to use Ant to generate a certificate as explained in:
http://www.asjava.com/ant/how-do-i-create-keystore-with-ant/
for people that don't want or don't have one (for dev environments, for instance), and allow, in some way to use yours if you have one for your institution.  

So, you should be able to configure if you want to use yours or you want a self generated one... 

If using their own certificate, then document where to put your keystore, and ask to configure the password and alias parameters.

If self generated, we will need to ask to configure these parameters (but we can provide some by default for dev purposes, so it would build without need to change this:
  <property name="verisign.key.storepass" value="xxxxx"/>
  <property name="verisign.key.alias" value="yyyyy"/>
  <property name="verisign.key.pass" value="zzzzzz"/>
<param name="CN" value="AsJava.com Group"/>      
<param name="OU" value="Jim"/>     
 <param name="O" value="AsJava.com"/>     
 <param name="C" value="US"/>

**Comment by doolse** [comment]
:+1: The only thing worth also checking is that self signed jars still allow webstart to escape the sandbox.

**Comment by ddelblanco** [comment]
I think I really never been able to make the admin console to be opened by the browser, I needed to launch it with command line based in the jnlp file that is downloaded. In chrome and in firefox. In both of them just downloads the file. Any

**Comment by doolse** [comment]
Yeah that's how you open it, normally jnlp files are associated with javaws
so just opening it rather than going to the command line is enough.

**Comment by ddelblanco** [comment]
I've created this code that allows to select with a build.property if we want to use an existing keystore or we want to create a new one self signed. In the case of the actual keystore, the keypass can be an empty string and it will work. 
https://github.com/equella/Equella/tree/issues/35
Please review it and if you consider good tell me and I will make the PR

**Comment by ddelblanco** [comment]
I've tested the "self-register" keystore. It is true that it doesn't work directly but It is possible to run it if the exception is added in:
${user.home}/.java/deployment/security/exception.sites
or using the java ControlPanel to add the trusted URL (really it does the same writting in that file)

Adding, http://localhost:8080/vanilla/  I can open it. 

So I will update the documentation to explain it. That should happen just for dev environments. Of curse for production people should add a signed keystore.

**Comment by ddelblanco** [comment]
Rebased with master, passed the tests, so merged and closing this one.
