### ISSUE TITLE
Reporting Methodology on https://github.com/equella/equella.github.io is a dead link

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#355]
Steps to Reproduce:

1. Navigate to https://github.com/equella/equella.github.io
2. Click on Reporting Methodology

Result: https://github.com/equella/equella.github.io/blob/master/gettingstarted/ReportingMethodology.md

**Comment by smclaughlin520** [comment]
Removed referenced - after researching the github history that page was merged into the Reporting Guide and the reference to that is already included on this home page.
