### ISSUE TITLE
Dead links in https://github.com/equella/equella.github.io

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#357]
1) https://github.com/equella/equella.github.io/blob/master/guides/WorkflowModerationGuide
2) https://github.com/equella/equella.github.io/blob/master/guides/ManageResourcesUserGuide.md
3) https://github.com/equella/equella.github.io/blob/master/guide/ClusteringConfigurationGuide.md
4) https://github.com/equella/equella.github.io/blob/master/guide/EmbeddedMetadataExtractionUserGuide.md
5) https://github.com/equella/equella.github.io/blob/master/guide/metadataSchemaConfigurationGuide.md
6) https://github.com/equella/equella.github.io/blob/master/guide/CopyrightConfigurationGuides.md
7) doesn't do anything: https://github.com/equella/equella.github.io#CopyrightResourcesManagementUserGuide.md

Are these just link errors, need to be removed, or...?

**Comment by smclaughlin520** [comment]
Link Issues corrected such that I all listed pages can now successfully launch
