### ISSUE TITLE
Register "com.github.equella" group id with sonatype (was "org.apereo.equella")

### ISSUE THREAD

**Issue by doolse** [equella/Equella#36]
Currently we have a couple of independently built code bases which need artefacts published:

* BIRT plugin
* Office integration

**Comment by bjagg** [comment]
We are currently awaiting name resolution

**Comment by bjagg** [comment]
Waiting on Legal

**Comment by drewwills** [comment]
Moving this one to 'publishing'.

**Comment by doolse** [comment]
This was registered and artifacts have been published
