### ISSUE TITLE
eqos-3820: Ability to disable session persistence in a clustered environment

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#363]
Ran script eqos-3820:
Put sessions.neverPersist=true in the optional-config.properties file on both nodes
Start up nodes
Log in and go to settings page
Shut down node that you are on
Click Search button

Expected Result: User is booted to the login page

Actual Result: 
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /xxx/searching.do.
Reason: Error reading from remote server

**Comment by doolse** [comment]
This worked fine for me, it really depends on the load balancer setup as to whether it fails over correctly. I was using a haproxy setup which successfully detected the failure and switched correctly
