### ISSUE TITLE
eqos-1931 Scripted portlet - HTML rendering 

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#365]
Create a new scripted portlet
Enter a Title and the text below in the Freemarker/HTML section
<ol> 
    <li>Test1</li> 
    <li>Test2</li> 
</ol> 
<ul> 
    <li>Test3</li> 
    <li>Test4</li> 
</ul>

The new scripted portlet should be added and the <ol> and <ul> should be rendered correctly

<ol> should produce a numbered list, 
<ul> should produce a list with bullet points. 

Ordered list works, bulleted list does not.

**Comment by emcgarrahan** [comment]
Also broken in 6.4QA3

**Comment by mrblippy** [comment]
Fixed
