### ISSUE TITLE
My tasks: missing skip button when moderating multiple tasks

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#373]
Steps to reproduce:
* Navigate to a user's My tasks page (containing multiple tasks)
* Click the blue select button on three tasks, then click the moderate selected button
* According to eqos-1898 we should expect to see "XofYtasks selected" and "Skip". But Skip is currently missing

**Comment by doolse** [comment]
@abidingotter is the test case true, is there meant to be a skip button?

**Comment by abidingotter** [comment]
There used to be a prev / next... See screenshot
![workflow screenshot 1](https://user-images.githubusercontent.com/1694589/31917661-5febc2ce-b8a4-11e7-99d3-e245b316172a.png)

**Comment by mrblippy** [comment]
Fixed
