### ISSUE TITLE
Clean-Thumbnail-queue task not visible on scheduledtasksdebug.do page

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#379]
According to testlink eqos-1705 Clean-Thumbnail-queue should be present on the <InstitutionURL>/access/scheduledtasksdebug.do page. 
At the moment it's not

**Comment by cbeach47** [comment]
@doolse mentioned it's not in the 6.5 release, however, I'm looking to get confirmation on when the scheduled task was removed.

**Comment by doolse** [comment]
According to @abidingotter this was functionality that was never released
