### ISSUE TITLE
Configure CustomBuildTasks to not delete files that are in use

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#38]
I ran ant release on Windows 10 and get the following error
`download-aether:
   [delete] Deleting directory C:\Users\nickc_000\edalex\repos\Equella\Platform\Infrastructure\CustomBuildTasks\lib

BUILD FAILED
C:\Users\nickc_000\edalex\repos\Equella\build.xml:124: The following error occurred while executing this line:
C:\Users\nickc_000\edalex\repos\Equella\Source\build.xml:46: The following error occurred while executing this line:
C:\Users\nickc_000\edalex\repos\Equella\Source\Plugins\build\build.xml:74: The following error occurred while executing this line:
C:\Users\nickc_000\edalex\repos\Equella\Interface\Build\build.xml:29: The following error occurred while executing this line:
C:\Users\nickc_000\edalex\repos\Equella\Platform\Infrastructure\CustomBuildTasks\build.xml:41: Unable to delete file C:\Users\nickc_000\edalex\repos\Equella\Platform\Infrastructure\CustomBuildTasks\lib\aether-api.jar
`
The build runs successfully when <delete dir="${lib}" /> is removed from line 41 of Platform\Infrastructure\CustomBuildTasks\build.xml. Seems like ant is holding onto the file and stopping it from being deleted??

**Comment by doolse** [comment]
No longer relevant with SBT build
