### ISSUE TITLE
Footer Link to Google Groups is Wrong

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#381]
User community goes to: https://groups.google.com/a/apereo.org/forum/#!forum/equella-users

Instead of: https://groups.google.com/a/apereo.org/forum/#!forum/equella-user

**Comment by emcgarrahan** [comment]
TSS icon as well.

**Comment by ddelblanco** [comment]
I've created the PR with this

**Comment by mrblippy** [comment]
Fixed: link now goes to https://groups.google.com/a/apereo.org/forum/#!forum/equella-users
