### ISSUE TITLE
Moderation History not displaying correct enteries

### ISSUE THREAD

**Issue by cathfitz** [equella/Equella#382]
The Moderation History dialog is not displaying all the entries it should when Basic details is selected. It's not showing the primary workflow events as it has in the past.

![image](https://user-images.githubusercontent.com/32081370/32208909-a908b83a-be59-11e7-9b66-00267447483c.png)
![image](https://user-images.githubusercontent.com/32081370/32208927-c351ba20-be59-11e7-9cde-8670ff6b1528.png)

**Comment by doolse** [comment]
I just looked into this and apparently this is on purpose and has been like this since before 2013 (don't have history earlier than that!) I can vaguely remember it working the way you've described but that must have been a very long time ago.
