### ISSUE TITLE
Download file viewer bypasses VIEW_RESTRICTED_ATTACHMENTS security

### ISSUE THREAD

**Issue by doolse** [equella/Equella#385]
If you restrict an attachment you shouldn't be able to download the file unless you have `VIEW_RESTRICTED_ATTACHMENTS`. However you can construct a URL which has the name of the file + the download viewer `"vi=save"` and download the file if you have VIEW_ITEM or VIEW_ATTACHMENTS.

**Comment by mrblippy** [comment]
Fixed
