### ISSUE TITLE
'Do not store DRM acceptances' checkbox not functioning correctly

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#395]
Found via testlink eqos-3953 

Steps to reproduce:
* Go to the Login settings page
* Check the 'Enable login via IP address' checkbox
* Check the 'Do not store DRM acceptances' checkbox, save
* Navigate to an item that has DRM on it
* According to the test case only Reject and Preview will be displayed as options - Accept should be omitted. But at the moment the accept button also appears.

This issue also happens in 6.4

**Comment by doolse** [comment]
Pretty sure that was changed on purpose, @abidingotter can you confirm?

**Comment by abidingotter** [comment]
It seems familiar.  Can't 100% confirm though.

**Comment by doolse** [comment]
Yeah this is another test case which hasn't been updated. The accept button has shown up for the auto logged in user since before we moved to git (2013), it just keeps the acceptance in the session rather than the database.
