### ISSUE TITLE
Merge plugins to speed up build and reduce bloat

### ISSUE THREAD

**Issue by doolse** [equella/Equella#404]
There is a large number of plugins (~420) which causes the build to take a long time to start. 
We can merge a number of these plugins fairly painlessly provided they meet some criteria:

* The don't have extension points
* They aren't depended on by plugins outside the merged set
* No resource files or language strings in common

**Comment by mrblippy** [comment]
A few display issues i have found so far:
Security manager
* Missing language string for hierarchy

Wizard controls
* User selector missing title/description
* Group selector missing title/description
* Email selector missing title/description
* Role selector missing title/description
