### ISSUE TITLE
tle upgrade binary for 6.5 stable 

### ISSUE THREAD

**Issue by bdolor** [equella/Equella#411]
### Description
We are upgrading our self hosted Equella instance this week and are wondering if there are plans release an upgrade binary for 6.5 along with the release of 6.5 Stable, as has been done with 6.5 Beta r21 https://github.com/equella/Equella/releases 

### System information 
Equella version: 6.4 QA3 r1397
OS: RHEL 6.9

![image](https://user-images.githubusercontent.com/2048170/34698698-549abd00-f48e-11e7-9c90-13ebef03d66c.png)

**Comment by cbeach47** [comment]
Hi @bdolor - you can find the upgrader by downloading the installer for 6.5-Stable, unzip it, and navigate to manager > updates.

**Comment by bdolor** [comment]
thank you @cbeach47
