### ISSUE TITLE
Quick contribute via Moodle drag and drop doesn't automatically populate item title and description

### ISSUE THREAD

**Issue by abidingotter** [equella/Equella#415]
See https://github.com/equella/moodle-mod_equella/issues/46

**Comment by abidingotter** [comment]
Please note, the fix will require the new Moodle Module in the current branch issues/47 (yes, 47)

**Comment by mrblippy** [comment]
After filling out the name and description fields and clicking the upload button i get a dialog saying ''Error occurred' (very informative)

I'm using moodle 2.4 with the issues/47 branch of the equella moodle module.

**Comment by abidingotter** [comment]
Charlie, can you enable the Moodle logs:
https://docs.moodle.org/dev/PHP_error_logs

There are also a bunch of admin settings in Moodle to turn on developer mode or something which may also be useful.

**Comment by mrblippy** [comment]
I had n00bed it up a bit, all sorted now.

Bug is fixed
