### ISSUE TITLE
Don't try to download reference-language-pack.zip from maestro.equella

### ISSUE THREAD

**Issue by ddelblanco** [equella/Equella#42]
Error getting http://maestro.equella.com/file/527661ac-9631-472e-96ea-7b224848b583/1/reference-language-pack.zip to /home/diego/dev/src/equellaGit/Equella/Source/Build/staging/prev-reference-language-pack.zip

Because in Source/build.xml we have this reference:
property name="prev.langpack.url" value="http://maestro.equella.com/file/527661ac-9631-472e-96ea-7b224848b583/1/reference-language-pack.zip"

**Comment by ddelblanco** [comment]
I;ll check the code too for other "mastro.equella" downloads. Now that we have a public git, that should be the place for all these things

**Comment by msultzaberger** [comment]
Removed the need to download the previous reference language pack zip by adding the zip to the source.
