### ISSUE TITLE
Email Selector Control: Entering invalid email address makes control unusable 

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#422]
Steps to replicate:
* Open a contribution wizard that contains an Email selector control
* Type an invalid email address and click the add button
* You will get a message saying 'Invalid email address', but the control will now be unusable until you restart the wizard.
![capture](https://user-images.githubusercontent.com/4625498/35127291-8dbecf5c-fd05-11e7-9257-ad2cfa3d46b4.PNG)

**Comment by abidingotter** [comment]
Couldn't reproduce on Edge, Firefox or Chrome.

**Comment by abidingotter** [comment]
@mrblippy Can you open the developer tools and see if there are any Javascript errors?

**Comment by mrblippy** [comment]
I can't reproduce it again either. Will close for now
