### ISSUE TITLE
REST endpoint for enumerating config settings

### ISSUE THREAD

**Issue by doolse** [equella/Equella#434]
This will be the endpoint which will be used by a new settings UI. 
Initially most of the settings will still be edited by accessing the existing settings page but eventually each type of setting should have it's own PUT method and URL for editing via JSON.

The endpoint will be along these lines:
```
GET /setting - List all settings which you can edit
                       
GET /setting/{settingtype} - Get a setting
PUT /setting/{settingtype} - Edit a setting
```
The setting list will initially contain data in the form:

```json
{ 
  "id": "admin_console", 
  "name": "Administration console", 
  "description": "Launch the administration console for advanced configuration of EQUELLA users and content",
  "group" : "extended",
  "links": {
    "web": "http://<inst>/jnlp/admin.jnlp"
  }
}
```

**Comment by cbeach47** [comment]
Took this for a spin - /api/settings require the 'accepts' header to be only application/json - we should allow it to be accessed from a browser like the other REST API endpoints.
