### ISSUE TITLE
Open source with user limit?

### ISSUE THREAD

**Issue by exing1984** [equella/Equella#438]
Since Equella as Open Source software, why still has user limitation?

**Comment by doolse** [comment]
Where are you seeing this user limit?

**Comment by exing1984** [comment]
Equella server administration, URL end by institutions.do?method=admin

Settings --> Licence management
![image](https://user-images.githubusercontent.com/2461984/36450404-bb08ae7c-16f2-11e8-8620-722213234341.png)

**Comment by cbeach47** [comment]
Once you upgrade to 6.5, that segment (License management) will no longer appear or be in effect.

**Comment by exing1984** [comment]
cbeach47, thanks for the reply.
From Internet, there is a Upgrade Guide for 6.5, mentioned that need to upgrade to V6.4 QA 4 first. Is anyone got QA4 release and upgrade guide?

Thanks.

**Comment by cbeach47** [comment]
What version of 6.4 are you on now?  I have successfully upgraded installs
from 6.4-qa3 to 6.5-stable.

On Feb 20, 2018 9:15 PM, "exing1984" <notifications@github.com> wrote:

cbeach47, thanks for the reply.
From Internet, there is a Upgrade Guide for 6.5, mentioned that need to
upgrade to V6.4 QA 4 first. Is anyone got QA4 release and upgrade guide?

Thanks.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/equella/Equella/issues/438#issuecomment-367200650>, or mute
the thread

**Comment by exing1984** [comment]
We are currently on V6.4 QA1

**Comment by cbeach47** [comment]
Especially if you are upgrading a test environment first, you should be
fine.  If you want to be safe, upgrade to 6.4-QA3 and then 6.5-stable, but
that's probably overkill.

**Comment by exing1984** [comment]
Where I can find the release file?

**Comment by cbeach47** [comment]
Sry, this slipped off my radar.  The latest demo builds of equella can be found on https://version.equella.net

**Comment by exing1984** [comment]
Thanks for the reply, i tried download version 6.5. Got error below:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C5E3CECA93E807D2</RequestId><HostId>j/dKGFieXY6RehXMZHqSLmFbUMm+6who4iRU3pKhH9tIwCfsZvsjg0H4QYEdSgD+hxUKcve32Ak=</HostId></Error>

Access Denied.

**Comment by cbeach47** [comment]
@exing1984 I'm seeing the same issue. @doolse has the access to version.equella.net, so he'll have to weight in on why it's not playing nice.

You can either use the 6.6 download from version.equella.net (which is working), or clone the repo locally, checkout the stable branch (which is 6.5) and build the 6.5 upgrader yourself.

**Comment by doolse** [comment]
I've fixed the download on version.equella.net, should work now.
