### ISSUE TITLE
Get a full EQUELLA running using SBT

### ISSUE THREAD

**Issue by doolse** [equella/Equella#44]
Using all thirdparty jars as part of the base classpath, get the EQUELLA server running and passing a subset of the automated tests.

**Comment by doolse** [comment]
There is an "sbt-build" branch for https://github.com/equella/Equella/tree/sbt-build 

Currently it's working and passes a small subset of the tests but a full autotest run will need to happen for a full verification.

**Comment by doolse** [comment]
This can be considered complete now, the installer and upgrade zips build and run. Any problems from here on can have their own issues created.

**Comment by drewwills** [comment]
Sounds good @doolse
