### ISSUE TITLE
New web UI component for lists of editable entities

### ISSUE THREAD

**Issue by doolse** [equella/Equella#464]
With the forthcoming effort to remove functionality from the admin console, we would like to have a consistent look and feel for the listing of editable entities (e.g. Courses / Reports / Schemas / Collections etc) 

---
At this stage we're it's going to be a basic search interface with a query and scrolling through results.

- [x] Creating new courses
- [x] Deleting courses
- [x] Create a link in the settings page
- [x] Scrolling through results

**Comment by cbeach47** [comment]
Makes sense to have that kind of an interface.  Given what the Admin Console can do, the entities should be able to have a generic CRUD structure as long as we allow for a customizable entity edit page (Hierarchy editor will be quite a bit different then a Report editor)

**Comment by doolse** [comment]
For 6.6 we've decided on a simple search like interface for selecting courses to edit. However we'll probably revisit this at some stage.

**Comment by cbeach47** [comment]
Maybe it's implicit, but will users be able to edit a course from this flow as well (not just create and search courses)?

**Comment by doolse** [comment]
@cbeach47 Yeah it'll be for deleting, creating and editing.
