### ISSUE TITLE
Settings.do broken in master

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#477]
Building with the latest from master, I get the following when trying to access `{eq-url}/access/settings.do` and the settings page does not appear.  @doolse  - does this work for you?
`
Error: Failed pattern match at Data.Maybe line 270, column 1 - line 270, column 46: e
[1] http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:11941
[1] http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:11890
http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:45655
[1] http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:6103
[1] http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:6103
[1] http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:6101
[1] http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:51186
http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:264
http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:438
<anonymous> http://localhost:8080/dev2/p/r/6.6.r82/com.equella.core/reactjs/index.js:1:2
`

Steps to recreate via command line:
> pull latest Equella repo @ master
> start sbt interactive
> clean
> compile
> prepareDevConfig
> equellaserver/run

**Comment by doolse** [comment]
It was working for me but I thought i'd try and reproduce it following your steps (apart from adding a step for editing the hibernate.properties) and it worked fine for me... 

The latest master is always built, autotested and deployed to https://betadev.equella.net/ so best check there if you think the build might be broken. Let me know if you'd like an institution on there.

**Comment by doolse** [comment]
Also it's probably best to use "test" instead of "compile" or "compile" followed by "resources", as I'm fairly sure that "compile" doesn't necessarily create all resources, only resources for projects that other projects compilation depends on. It seemed to be enough to get the settings page going at least.

**Comment by cbeach47** [comment]
Using `test` worked to allow the settings page to appear.  Are you recommending that the sequence be either of the following, or just the first?

> test
> equellaserver/run

or 

> compile
> resources
> equellaserver/run

Having an institution on betadev would be helpful, thank you :)

**Comment by doolse** [comment]
Either is fine, use test if you want to run the unit tests! @cbeach47  Could you send me an institution export that you'd like me to upload or is vanilla fine?

**Comment by cbeach47** [comment]
@doolse - a vanilla institution is fine.
