### ISSUE TITLE
Watching a yarn project

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#479]
In the [documentation](https://github.com/equella/Equella/blob/master/CONTRIBUTING.md), it's given that:
> Currently there are number of separate JS bundles which are generated and you could develope them easier by running a yarn "watched build" script. E.g. to develop the settings page:
> 
> ~/Source/Plugins/Core/com.equella.core/js$ yarn run dev:settings

I am assuming this works, but my setup is off.   When I run it, I get:
> ~/repo/Equella/Source/Plugins/Core/com.equella.core/js$ yarn run dev:settings
> yarn run v1.5.1
> error An unexpected error occurred: "Command \"dev:settings\" not found.".

Are there any tips/tricks to get this working the first time?

**Comment by abidingotter** [comment]
I believe it should be dev:index

**Comment by cbeach47** [comment]
Thanks, that does work nicely.  

Leaving this open in case @doolse was trying to get at something else with `dev:settings`.

**Comment by doolse** [comment]
The documentation was out of date, it's all been moved into a single javascript bundle now.
