### ISSUE TITLE
New UI Accessibility issues

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#483]
Based on testing results form the aXe accessibility tool https://axe-core.org/

- [x] Task, Notifications, Logout buttons should have discernable text https://dequeuniversity.com/rules/axe/3.0/button-name?application=AxeChrome
- [x] ul elements in left menu should contain li elements https://dequeuniversity.com/rules/axe/3.0/list?application=AxeChrome
- [x] new-equella-logo.png requires alt attribute
- [x] Task, Notifications don't have sufficient colour contrast https://dequeuniversity.com/rules/axe/3.0/color-contrast?application=AxeChrome
- [x] Thumbnail images on search results require alt tags
- [x] All pages should sontain h1 element https://dequeuniversity.com/rules/axe/3.0/page-has-heading-one?application=AxeChrome
- [x] Search input box requires label tag https://dequeuniversity.com/rules/axe/3.0/label?application=AxeChrome

**Comment by abidingotter** [comment]
Tried to use MenuList instead of List but doesn't seem to be included in @doolse purescript-react-mui repo.

**Comment by abidingotter** [comment]
" Task, Notifications don't have sufficient colour contrast "  I suspect this was in their disabled form?  I'd be ok with that
