### ISSUE TITLE
Workflow - "choose moderators based on item metadata" doesn't work with remote accounts

### ISSUE THREAD

**Issue by phette23** [equella/Equella#484]
Steps to recreate:

- create a Workflow with a Workflow Task using the setting "Choose moderators based on a list of users stored in item metadata"
- contribute an item and populate the metadata node targeted above with the username for a remotely managed account, e.g. LDAP
- sign in as the remote user, there's no notification in their tasks nor do they receive a notification email

I've been troubleshooting this issue with @cbeach47 who might be able to describe the behavior more accurately. It looks like EQUELLA just doesn't query LDAP when it's look for moderators with this setting. I'm not sure if this has always been the case…I feel like it was working back in 6.4 but I don't have specific examples. All our users are LDAP and we would like to use this feature to avoid setting dozens of decision points in workflows (you can outsource the moderator logic to ASC scripts, which is far more flexible and easier to update).

I've tested on the 6.5 release and 6.5 stable as of about three weeks ago.

**Comment by cbeach47** [comment]
@phette23 - I tested this flow with 6.5-r20 and the RC of 2018.2 (on 2018/12/20) with LDAP users - every time the item went into moderation and the LDAP user was notified in the 'my tasks' area.  We'll have to dig a bit deeper to see what's different in your setup.

**Comment by phette23** [comment]
An update on this—it's not clear from documentation, at least any that I have seen, but the way to handle multiple moderators with this feature is to list each moderator in a separate metadata node e.g.

```xml
<xml>
  <local>
    <moderator>johndoe</moderator>
    <moderator>cortez</moderator>
    <moderator>m2n9b3</moderator>
  </local>
</xml>
```

as opposed to a single element with a comma-separated list as its text value. I can't recreate my original problem with single values for moderator usernames. Going to close this until I have a better demonstration of a probelm.
