### ISSUE TITLE
Error adding Kaltura resource

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#490]
Caused by the great plugin merge of 2018

Template not found for name "com.tle.web.wizard.controls.universal@/common-edit-handler.ftl" The name was interpreted by this TemplateLoader: com.tle.web.freemarker.CustomTemplateLoader

Steps to reproduce:
* Open a contribution wizard containing a kaltura attachment control
* Search for a kaltura video, select it and press the green add button
* You will get an error message

**Comment by doolse** [comment]
Fixed on the Kaltura repo
