### ISSUE TITLE
Expose FileHandleScriptType.getHandle() as a supported function

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#500]
The following function is useful, but it's not exposed in the API, and the comments say it's for internal use only.  Discuss why this might be, and barring any blocking reasoning, expose the function officially.

https://github.com/equella/Equella/blob/136b76ffd71515193bad49596de9d9bf92db38b5/Source/Plugins/Core/com.equella.core/src/com/tle/web/scripting/impl/FileScriptingObjectImpl.java#L242

**Comment by cbeach47** [comment]
@doolse  /  @abidingotter - any thoughts on why it might be unwise to expose this officially in the API docs?

**Comment by doolse** [comment]
The whole point of `FileHandleScriptType` is to abstract `FileHandle` so it stays private. What do you need to do with `FileHandle` directly?

**Comment by cbeach47** [comment]
I've opened #506 instead - I don't see value-add specifically in exposing the `FileHandle` if there is another way to find the Staging path.  

@doolse - just out of curiosity, what is the reasoning behind keeping the `FileHandle` private?

**Comment by doolse** [comment]
@abidingotter Will know about the scripting API, I imagine there is a way to get the absolute path of a FileHandleScriptType. 
The scripting API was re-designed to have well defined interfaces specifically to prevent people writing scripts against our internal implementations which meant that we could no longer change them without breaking peoples scripts.

**Comment by abidingotter** [comment]
@cbeach47 The idea of not exposing the FileHandle is that it's internal Equella code, and we should be able to freely modify it without having to worry about external usage of it breaking.  (E.g. removing a method on the FileHandle object that someone is using in a script).  The script objects form a contract and they should only ever be added to, never modified or deleted.
