### ISSUE TITLE
Create a function in the FileScriptObject to obtain the Staging path

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#506]
At times it's useful to know the `hash` and `uuid` of the Staging path for the current item.  For example, if you want to run a system process to check one of the files you are about to persist to the filestore, you need the `hash` and `uuid` to build the file path.

Enhance the FileScriptObject API (referenced in the script as `staging`) to include a call `getPath()` that returns the `hash/uuid` of the current staging folder.

**Comment by doolse** [comment]
@abidingotter Does this exist already somewhere?

**Comment by abidingotter** [comment]
@cbeach47 @doolse  The system script object accepts script file handles as the parameters, as well as attachment script objects or indeed actual path strings.  Is system.execute("someexe", [staging.getFileHandle(yourfilename)]) not sufficient?

**Comment by cbeach47** [comment]
@abidingotter - interesting.  Looks like that'll do the trick with a bit of supporting logic to grab the parent folder.  Thanks for the tip.
