### ISSUE TITLE
New search page looks bad on small screens

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#517]
It looks like this on my phone (galaxy j5 pro) 
![unnamed](https://user-images.githubusercontent.com/4625498/41134966-80a4eae2-6b12-11e8-9b96-d57796e44e90.png)

The refine panel shouldn't present on screen at all times, there's not enough room for it

**Comment by jonfackrell** [comment]
Isn't this new template supposed to be responsive?

**Comment by mrblippy** [comment]
Yes, that's why the bug was logged

**Comment by doolse** [comment]
The template is responsive, (e.g. the menu disappears when the screen shrinks). 
However the new UI's search page is just a prototype of what will eventually be a full replacement for the old search page, which is why it can be switched off completely. That page will be designed to be responsive.
