### ISSUE TITLE
Add a new column to audit log table and store HTTP referrers in it

### ISSUE THREAD

**Issue by doolse** [equella/Equella#521]
It would be useful for reporting purposes if we stored HTTP referrers in the audit log when appropriate:

* Login events
* Item/view view events

It would be handy if the new column in the audit log was available for new log fields in the future, so we would ideally like to use a column suitable for querying/indexing schemaless data (JSONB or XML)

---
EDIT:
The new column is `meta` in the `audit_log_entry` table and it contains JSON data.
The referrer is stored in the `referrer` field, e.g. 

```json
{
  "referrer": "http://somehost.com/somepath?query"
}
```

**Comment by doolse** [comment]
The privacy API needs to return this new data too

**Comment by mrblippy** [comment]
Verified in master
