### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by rkhyd** [equella/Equella#522]
Hello
i receive this error when installing the Equella package in ubuntu 16.04
`[error] java.lang.RuntimeException: Running yarn script 'browserify' in dir /var/www/Equella/Source/Plugins/Core/com.equella.core/swaggerui failed
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at Common$.runYarn(Common.scala:66)
[error]         at $46f5c77b0cec765a8d8e$.$anonfun$$sbtdef$1(/var/www/Equella/Source/Plugins/Core/com.equella.core/build.sbt:84)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Running yarn script 'build' in dir /var/www/Equella/Source/Plugins/Core/com.equella.core/js failed
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at Common$.runYarn(Common.scala:66)
[error]         at $67cea4b4e78a8791a437$.$anonfun$$sbtdef$1(/var/www/Equella/Source/Plugins/Core/com.equella.core/build.sbt:93)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (com_equella_core / Compile / managedResources) Running yarn script 'browserify' in dir /var/www/Equella/Source/Plugins/Core/com.equella.core/swaggerui failed
[error] (com_equella_core / buildJS) Running yarn script 'build' in dir /var/www/Equella/Source/Plugins/Core/com.equella.core/js failed
[error] Total time: 875 s, completed Jun 18, 2018 5:59:53 AM`
The full installation log is attached.. 
Please let me know how to fix the issue. thanks
[equella_install_output.txt](https://github.com/equella/Equella/files/2110072/equella_install_output.txt)

**Comment by doolse** [comment]
Looks like you have an old Node install - 
```
warning You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
```

Probably best to install v8 but it was originally tested with v6.11.4

**Comment by rkhyd** [comment]
Thank you doolse for your reply. 
i have used the git repo listed at https://github.com/equella/Equella and started the install process.
please point me where to ge the v8 as suggested by you. thanks for your co-operation.

**Comment by doolse** [comment]
You can find node releases here - https://nodejs.org/en/

**Comment by rkhyd** [comment]
Node was not installed in the server. The prerequisite was not mentioned in the install steps. So assumed that it will be automatically installed. Installed the node v8 package and then the installer ran smoothly without errors and the installer file is now generated.
I was also able to install the package. 
What would be the default credentials to login into the http://<ipaddress>:3000
