### ISSUE TITLE
Rollover activations: course dropdown should be a smart search

### ISSUE THREAD

**Issue by abidingotter** [equella/Equella#528]
The Course dropdown on the rollover activation dialog should be replaced with an "autocomplete" control similar to:
https://select2.org/data-sources/ajax

The course filter on the Manage Activations screen should use the same control and the Course selection dialog should be deleted.

**Comment by mrblippy** [comment]
https://github.com/equella/Equella/issues/557

**Comment by edalex-ian** [comment]
This has been further addressed in #642. @doolse is updating the autotests to support the rework, then it'll be 'Ready for Testing'.

**Comment by SammyIsConfused** [comment]
It works fine, but in the Activate Attachments screen, it looks like this:
![mismatched dropdown lengths](https://user-images.githubusercontent.com/24543345/49843326-ecc4ff80-fe12-11e8-956f-c34a68da896e.png)
shouldn't it be the same width as the other drop down on the screen for consistency?
I can change this, if you'd like.

**Comment by edalex-ian** [comment]
Cool, if you could do a quick fix that'd be great @SammyIsConfused :+1:

**Comment by SammyIsConfused** [comment]
#650
It's a little trickier than I first thought, at least without making a mess of the CSS. This is a low priority issue, as it doesn't break functionality and only happens in one place. I'll work on something else right now.
