### ISSUE TITLE
Replacing a file attachment with a file of the same name doesn't work correctly

### ISSUE THREAD

**Issue by doolse** [equella/Equella#531]
Currently if you try and replace it with the same file it thinks it already exists and puts a (2) next to the filename.

Also if you have a corrupt item which has the actual file missing it instead just allows you to upload it but deletes it immediately when it gets replaced.

EDIT: 
It was worse than this 
- Add resource - upload a single file with the attachment dialog - save
- Add resource - simply close the dialog 
- Original uploaded file would be deleted but attachment would still exist

**Comment by mrblippy** [comment]
Verified in master, 6.6 and 6.5
