### ISSUE TITLE
Attachment control hangs if a Youtube video didn't return expected values

### ISSUE THREAD

**Issue by nelson-edalex** [equella/Equella#540]
When user contributes a Youtube attachment, contribution screen will hang if the selected Youtube video did not some expected values, e.g. number of likes.

**Comment by nelson-edalex** [comment]
Below is the stack trace:
<tr><td>10:41:05,347</td><td>067d1e4e-3fa7-43f0-b6ef-77031db71cea</td><td><font color="#993300"><strong>ERROR</strong></font></td><td>AjaxExceptionHandler<
/td>
<td>Error during ajax request</td></tr>
<tr><td bgcolor="#993300" style="color:White; font-size : xx-small;" colspan="5">com.tle.web.sections.ajax.exception.AjaxException: java.lang.NullPointerEx
ception
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.ajax.handler.StandardAjaxRenderContext.processEvent(StandardAjaxRenderContext.java:414)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:311)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.SectionUtils.renderSectionResult(SectionUtils.java:764)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.standard.dialog.AbstractDialog.getSelectedRenderer(AbstractDialog.java:394)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.standard.dialog.AbstractDialog.renderHtml(AbstractDialog.java:235)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:245)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.ajax.handler.StandardAjaxRenderContext.processEvent(StandardAjaxRenderContext.java:410)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:311)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.template.RenderTemplate.renderHtml(RenderTemplate.java:155)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.registry.SectionsControllerImpl.renderForward(SectionsControllerImpl.java:103)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:79)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:81)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:39)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at java.lang.Thread.run(Thread.java:748)
<br>&nbsp;&nbsp;&nbsp;&nbsp;Caused by: java.lang.NullPointerException
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.controls.youtube.YoutubeHandler.renderDetails(YoutubeHandler.java:473)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.controls.universal.AbstractDetailsAttachmentHandler.render(AbstractDetailsAttachmentHandler.java:206)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.controls.universal.UniversalResourcesDialog.getDialogContents(UniversalResourcesDialog.java:244)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.standard.dialog.AbstractDialog.prepareModel(AbstractDialog.java:267)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.standard.AbstractRenderedComponent.renderHtml(AbstractRenderedComponent.java:251)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.standard.dialog.AbstractDialog.renderHtml(AbstractDialog.java:237)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:245)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.ajax.handler.StandardAjaxRenderContext.processEvent(StandardAjaxRenderContext.java:410)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    ... 44 more
</td></tr>

**Comment by mrblippy** [comment]
Fixed
