### ISSUE TITLE
Autocomplete dropdowns not functioning when accessibility mode is enabled 

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#546]
Related to #541
Autocomplete dropdowns are not usable by users that have accessibility mode enabled (on user profile page)

![flopdown](https://user-images.githubusercontent.com/4625498/43872455-1abfdafa-9bc5-11e8-8b9d-92e6389733c8.png)

**Comment by abidingotter** [comment]
Switched to "selectWoo" https://github.com/woocommerce/selectWoo which is an active fork of Select2 (select2 appears to have become inactive as of about a year ago) which has focussed on accessibility improvements, hence negating the need to revert to normal dropdowns when Accessibility Mode is active,

**Comment by mrblippy** [comment]
👍👍👍
