### ISSUE TITLE
Research need for Kaltura and replace/remove

### ISSUE THREAD

**Issue by bjagg** [equella/Equella#55]
Kaltura is under a GPL license. Eliminate or find alternative.

**Comment by drewwills** [comment]
Can we make this item a pluggable component somehow?  Hide it behind a "pluggable, interface-based abstraction?"  (And simply not provide the Kaltura impl, if we're not legally allowed.)

**Comment by emcgarrahan** [comment]
@bjagg to continue to look into this one.
It is already a pluggable component.

**Comment by emcgarrahan** [comment]
- Remove it and provide instructions to go download it.

**Comment by drewwills** [comment]
https://www.apache.org/legal/resolved.html#optional

**Comment by cbeach47** [comment]
Confirmed removing the Equella/Source/Plugins/Kaltura folder, and the Kaltura dependency from Equella/Source/equellaserver/build.sbt will build Equella without Kaltura.

Using the test [TestEnablingKaltura.html](https://equella.github.io/tests/migration/64QA3-to-OS/TestEnablingKaltura.html) as a guide, I confirmed that starting with 6.4-QA3 with Kaltura configs / attachments, then upgrading to the open source version without Kaltura and using Equella didn't throw any errors, though there are some things to watch for.
I then confirmed upgrading to the open source version built with Kaltura 'brought back' Kaltura as expected.  I did find one error, but I think it's more of Equella admins being aware, then something we should fix in the code:

- Save a collection that originally had kaltura configured via the code base without Kaltura.
- After enabling Kaltura in the code, try to delete the Kaltura attachment on an item that was originally setup with a Kaltura attachment.  It throws an AJAX error, and there's a NPE in the logs.
- Edit the collection to enable Kaltura as an attachment type, and you can delete / add Kaltura attachments now without errors.

Need to confirm with @doolse / @drewwills where the Plugins/Kaltura code should live.

**Comment by cbeach47** [comment]
Note:  Running Equella without Kaltura, a previously configured Kaltura widget gives a polite message "No resource types have been configured for this control. Please contact your system administrator ".

**Comment by cbeach47** [comment]
Opened pull request #81 .  Working with Drew to create a new repo to push the removed Equella Kaltura code into.

**Comment by drewwills** [comment]
https://github.com/equella/Equella-Kaltura

**Comment by cbeach47** [comment]
Moved over the code and updated the docs.
