### ISSUE TITLE
Additional issues occuring due to Contentservlet (#549) fix

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#551]
- [x] Error uploading scrapbook files  in old and new UI (Must set an ajax upload url for fileupload)
- [x] Left menu displays below main content when adding/editing custom links (on old ui)
- [x] Reset to default button on HTML editor toolbar settings page doesn’t do anything (new ui) 
- [x] Accessing institution url without trailing / goes to 404 page, instead of redirecting to logon.do
- [x] Can't return selections in old ui
![return selections](https://user-images.githubusercontent.com/4625498/44834472-a6d59880-ac74-11e8-86c4-1a822441edba.PNG)
- [x] Close button on selection dialog doesn't close
- [x] A two page wizard with editboxes as the first control will copy the value from the first page into the second page

**Comment by doolse** [comment]
- [ ] New UI - "Leave site? Changes you have made..." dialog shows up when it shouldn't and doesn't show up when it should:
  - Contribute / Select a wizard / Click another menu link - doesn't stop you
  - Contribute / Select a wizard / Save / My Resources / Click an item - tries to stop you

**Comment by mrblippy** [comment]
Verified in 2018.2
