### ISSUE TITLE
Course selection dialog only showing archived courses

### ISSUE THREAD

**Issue by doolse** [equella/Equella#568]
This has been fixed in master already but apparently it made it out to 6.6

**Comment by mrblippy** [comment]
Verified in 6.6 and master

**Comment by mrblippy** [comment]
I originally marked this as verified in 6.6. But it appears to still be broken in the latest 6.6. Not sure how that happened, I maybe misunderstood what area needed to be tested.

You can see it in action by going to Manage Activations -> Perform an action -> Rollover activation

6.6 still uses the non autocomplete course selector, so the fix will need to be different than in 2018.2

**Comment by edalex-ian** [comment]
Fix done by @doolse
