### ISSUE TITLE
API for interacting with selection session / integration session

### ISSUE THREAD

**Issue by doolse** [equella/Equella#569]
Selection sessions need an API for adding/removing/returning results back to their caller.

This call should be a form post from the browser as it will eventually redirect back to the caller
`POST /api/selection/{sessionid}/return?integid={integid}`

`POST /api/selection/{sessionid}/add`
BODY:
```json 
{
  "key": {
     "uuid": "UUID",
     "version": "1",
     "type": "a|p",
     "attachmentUuid": "?UUID",
     "folderId": "?folderId", 
     "url": "?url"
  },
  "title": "Title of selection"
}
```

**Comment by edalex-ian** [comment]
@doolse and @cathfitz confirmed working.
