### ISSUE TITLE
Attachment control - unzipping files - 6.5

### ISSUE THREAD

**Issue by carl-edalex** [equella/Equella#576]
Tested in 6.5 r.26

In 6.5 r25, if you use the "Add a resource" link to launch the attachment control popup, uploaded a zip file and in that same popup, unzipped the file and selected one of the files to display on the item summary screen, the links to the zip file and the item in the unzipped file would contain in the url:

<equella server>/file/<item uuid>/<version>/**_uploads/<uuid>**/<zip name>/<directory>/<filename>

The link of course would not work because the path was wrong.  But if you either 
1.  dragged and dropped the file (in the contribution wizard, not the popup) and then edited the uploaded zip attachment, unzip, select attachments to display, save the changes; or

2. launch the attachment control, upload a zip file, save the attachment control, edit the attachment, unzip, select attachments to display, save the changes

then everything is fine.

Now in 6.5 r26, we can avoid the bug with the steps above, but if the bug is triggered, because of https://github.com/equella/Equella/issues/574, the _uploads folder is deleted, the zip file's directory is not in the filestore and the zip file is located in _zips/uploads/<uuid>/<zipfile name>.

**Comment by mrblippy** [comment]
Fixed
