### ISSUE TITLE
Manual Data Fixes is missing from the settings page

### ISSUE THREAD

**Issue by carl-edalex** [equella/Equella#578]
#version
#Fri Sep 07 06:08:29 UTC 2018
version.display=6.6-Stable.Edalex
version.mm=6.6
version.mmr=6.6.r11
version.commit=gb6c5a72

Manual data fixes is missing from the settings page.  It is still accessible by manually going to: .. access/manualdatafixes.do

**Comment by mrblippy** [comment]
Verified in 2018.2
