### ISSUE TITLE
Create the Install file for the Equella OS Release

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#58]
- [x]  Create the Installer for Equella - including any required handling for non-OS dependencies

- [ ] Update the Aperero website with a link to the Install File(s)

- [ ] Update the GitHub documentation with Install File Links and Info

**Comment by bjagg** [comment]
Is this something Chris can tackle?

**Comment by cbeach47** [comment]
I would think so, but it'll be blocked until we have a working build via SBT.

**Comment by drewwills** [comment]
@cbeach47 -- Do we now have a working SBT build?  Can we consider this one un-blocked?

In either case, I'm going to move this one to the 'publication' milestone.
