### ISSUE TITLE
Term selector error - New UI

### ISSUE THREAD

**Issue by alejopachons** [equella/Equella#581]
Currently, term selector in the new UI has a bad resizing and the content is under the menu.

![captura](https://user-images.githubusercontent.com/22798883/46038148-f1a9cb00-c0cf-11e8-8c3e-3cec0a407aaf.PNG)

**Comment by cbeach47** [comment]
Thanks for flagging this @alejopachons !

**Comment by mrblippy** [comment]
Fixed
