### ISSUE TITLE
New drop down control steals focus on pressing space 

### ISSUE THREAD

**Issue by doolse** [equella/Equella#583]
* Manage items
* Filter -> Filter by Status - Check "Only show items in moderation"
* Filter by workflow - Select a workflow
* **Ensure filters are left open**
* Click on search query box and press space
* The filter by workflow drop down will appear in the top left

**Comment by mrblippy** [comment]
In edge you have to click the search query box twice to steal the focus away from the filter by workflow dropdown

**Comment by doolse** [comment]
This no longer applies as the new drop downs were reverted to the old one.
