### ISSUE TITLE
Search page configuration API

### ISSUE THREAD

**Issue by doolse** [equella/Equella#587]
We need an API for configuration of a search page, something along the lines of:
```json 
{
   "id":"UUID",
   "index":"item",
   "sections":{
      "query":[

      ],
      "results":[
         {
            "type":"sort",
            "default":"relevance",
            "editable":false
         }
      ],
      "filters":[
         {
            "type":"collection",
            "default":[
               "uuid"
            ],
            "editable":true
         }
      ]
   }
}
```

Each of the "sections" is optional and if not supplied it means use the default.

Each value in each section represents a control which can affect the search results or display in some way. 

Each control has it's own configuration but usually they will contain settings which allow:

* Defaulting to a particular value (e.g. filtering to a particular collection)
* Allowing or disallowing editing of the value in the UI (e.g. selecting which collection to filter on)

Initial controls will include (with example)
- [x] Sort control
  ` { "type": "sort", "default": "relevance", "editable": true }`
- [x] Collection filter
  ` { "type": "collections", "collections": ["uuid1", "uuid2"], "editable": true }`
- [x] Owner filter
  ` { "type": "owner", "default": "userid", "editable": true }`
- [x] Facet control
  ` { "type": "facet", "title": "Title", "node": "/xml/item/node }`
- [x] Last modified range
  ` { "type": "modifiedWithin", "default": 100000, "editable": true }`

All the endpoints should be under `api/searches`

`GET|PUT config/{UUID}` 
`POST config` create new config
`GET|PUT page/{pagename}` - Get or change the association of a particular config with an openEQUELLA page (e.g. search, manage, tasks..)
`GET page/{pagename}/resolve` - Get the config for a particular page, resolving any defaults.

All PUT's and POST's are secured behind EDIT_SYSTEM_SETTINGS. GET's are public

**Comment by mrblippy** [comment]
Verified in master
