### ISSUE TITLE
Faceted search requires EDIT_SYSTEM_SETTINGS

### ISSUE THREAD

**Issue by nelson-edalex** [equella/Equella#591]
In order for the faceted search to work, EQUELLA requires a user to have, at minimum, EDIT_SYSTEM_SETTINGS under Institution > System Settings > Search Settings.

If user does not have this permission, he only sees "Modification date" and "Owner" in the right menu in faceted search.

Viewers and searchers should not need EDIT_SYSTEM_SETTINGS permissions to do searches.

**Comment by mrblippy** [comment]
@doolse  how do you add new facets in the settings? I don't see it where it used to be
![capture](https://user-images.githubusercontent.com/4625498/48590324-2846e800-e993-11e8-94d8-a22a9feff851.PNG)

**Comment by mrblippy** [comment]
Fixed in master and 6.6
