### ISSUE TITLE
User need VIEW_ITEM permission to see the search result list in new UI

### ISSUE THREAD

**Issue by nelson-edalex** [equella/Equella#594]
In old UI, user with DISCOVER_ITEM permission can see search results and view item summary page.
In new UI, user requires VIEW_ITEM to see these pages.

https://screencast.com/t/4pkV6xyBKU

**Comment by mrblippy** [comment]
Fixed

**Comment by doolse** [comment]
> Re-opening briefly - there's no audio in the screencast, so not sure I understand correctly - Is the expected behavior in the new UI for DISCOVER_ITEM and VIEW_ITEM to be required for results to be returned?

You only need DISCOVER_ITEM to have results returned in the search, if you don't have VIEW_ITEM you won't see the attachments (thumb etc) in the search result list

**Comment by cbeach47** [comment]
:+1:  sounds good.
