### ISSUE TITLE
Create and Establish repos for additional Equella ecosystem components

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#6]
Decompose these into multiple issues as identified
These are items known so far

- Equella Metadata Utility (EMU)

- Equella Bulk Importer (EBI)

- Basic/stripped down export and import utilities

- Several simple scripts frequently used by clients (e.g. ping utility, etc).

Would like Edalex to review and add any additional items they are aware of.

Edit: 

Other repos for artifacts which are published outside of the main build:

- BIRT reporting plugin
- JPF eclipse plugin
- Office integration

**Comment by emcgarrahan** [comment]
Discuss this one with Jolse...

**Comment by drewwills** [comment]
@doolse -- This one seems like a good one for you.

Please remember to scrub secrets & remove history, just as we did with the main sources.

**Comment by emcgarrahan** [comment]
Office and BIRT are completed - waiting for Maven ID.

**Comment by cbeach47** [comment]
Blocked by #36

**Comment by drewwills** [comment]
I don't believe the task to "Create and Establish repos" for these components is blocked.

Are all the repos created?  (At least the immediate/pre-incubation set?)  Do they all have sources?  If so, I'd say this item is complete.  Could someone with knowledge of those facts do a quick review and close this ticket?

If there are 1 or 2 remos that we still need, let's create specific tickets for those (and close this one).

**Comment by doolse** [comment]
The 3 repos mentioned in this ticker have been created.
