### ISSUE TITLE
Remove links and references to Pearson, equella.com, and other our of date links in the UI

### ISSUE THREAD

**Issue by ddelblanco** [equella/Equella#60]
Search an update all the references to:

Pearson
equella.com

**Comment by cbeach47** [comment]
Would be good to perform a search for 'TLE' and 'Learning Edge' as well.  There are some that could be client facing and I can help determine what those are.  @ddelblanco - what did you use to search the Equella repo for 'Pearson' and 'equella.com'?

**Comment by ddelblanco** [comment]
I just searched in eclipse with a plugin that exports to csv the searches
https://marketplace.eclipse.org/content/eclipse-search-csv-export

**Comment by cbeach47** [comment]
@ddelblanco - I didn't the following in your todo docs, but noticed while I was running the gui installer:

On the splash page of the java gui installer, the 'current' Equella user community is linked: https://neoconnect.pearson.com/groups/equella?view=documents/

**Comment by ddelblanco** [comment]
Yes, that has been corrected

**Comment by ddelblanco** [comment]
https://github.com/equella/Equella/pull/75
