### ISSUE TITLE
"Try it out" button in apidocs.do only works on new UI (EQ 6.6)

### ISSUE THREAD

**Issue by nelson-edalex** [equella/Equella#601]
When EQUELLA's new UI is turned on, apidocs.do works well.
If new UI is turned off, accessing apidocs.do and expanding the APIs are fine.
But if I click the "Try it out" button, there is a Javascript error.
![image](https://user-images.githubusercontent.com/28520211/48591526-672b6c80-e998-11e8-9fe2-38fcfed4be23.png)
The whole apidocs.do page is reloaded instead of opening up the fields for testing the API.

**Comment by doolse** [comment]
@nelson-edalex I can't reproduce this, are you on the latest stable?

**Comment by nelson-edalex** [comment]
@doolse: I was on 6.6r5.  It's working after upgrade to latest 6.6r17.
Sorry for that.
