### ISSUE TITLE
New favicon.ico

### ISSUE THREAD

**Issue by edalex-ian** [equella/Equella#604]
Current favicon.ico is the old Pearson one, needs to be replaced with an open source specific one.

@mrblippy is currently looking at this as time permits, so assigning accordingly.

**Comment by SammyIsConfused** [comment]
Confirmed working in master.

**Comment by SammyIsConfused** [comment]
Gonna check the admin console too, now I think about it.

**Comment by SammyIsConfused** [comment]
![screenshot from 2018-12-13 12-06-49](https://user-images.githubusercontent.com/24543345/49908674-cadd8280-fecf-11e8-95a9-e5c37113e069.png)
Found one! The admin console window's icon is the old one.

**Comment by SammyIsConfused** [comment]
Confirmed fixed on betadev.
