### ISSUE TITLE
SBT build loose ends

### ISSUE THREAD

**Issue by doolse** [equella/Equella#61]
- [x] Admin console jnlp and jar
- [x] Version number (used to be based off git commit, keep this?)
- [x] In place editor applet
- [x] BIRT reporting runner
- [x] Convert dev config setup from ant
- [x] Delete obsolete ant scripts and paths to prevent confusion

**Comment by cbeach47** [comment]
*Note:* until the admin console is working from the web ui, you can launch it via cd'ing to the source of Equella, and running:
`sbt adminTool/run`

**Comment by doolse** [comment]
Turns out the in place editor applet was disabled in 2013
