### ISSUE TITLE
Update screenshots that are displayed on dashboard 

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#613]
There are help screenshots that are displayed on the user's dashboard when they don't have any portals. At the moment the screenshots are ollllllddd, so still have lots of references to the old logos. We should change that.

![capture](https://user-images.githubusercontent.com/4625498/48878905-9725b480-ee5d-11e8-88e0-a403c3dc0220.PNG)

**Comment by SammyIsConfused** [comment]
This works now, however it is quite confusing when in the New UI, as none of the instructions apply.
