### ISSUE TITLE
Quick contribute doesn't work when selectMultiple is selected

### ISSUE THREAD

**Issue by doolse** [equella/Equella#616]
**Describe the bug**
When using the Quick Contribute "portlet" on the selection session homepage, it only works if selectMultiple is false. It returns an error page otherwise.

Because the quick contribute file selector is now an AJAX upload, the return from selection session needs to always be done on the after file upload request instead.

**To Reproduce**
1. Use an Integration which is setup to "selectMultiple" e.g. Moodle
2. Use the Quick Contribute portlet to select a file
3. BOOM

**Comment by mrblippy** [comment]
Verified in master
