### ISSUE TITLE
Upgrade flamingo

### ISSUE THREAD

**Issue by doolse** [equella/Equella#62]
Flamingo is a swing component set which is actually in maven, should be just a matter of changing the flamingo dep in Source/Server/equellaserver/build.sbt to:

"com.github.insubstantial" % "flamingo" % "7.3"

and fix any compile errors.

**Comment by cbeach47** [comment]
We are unable to test due to the current setup of the File Manager (java applet) and modern browsers.  Plan to discuss soon.
