### ISSUE TITLE
Doing a double submit complains about missing JS var

### ISSUE THREAD

**Issue by abidingotter** [equella/Equella#620]
**Describe the bug**
JS error on double submit

**To Reproduce**
Press any button twice whilst Equella is still thinking about it.  E.g. hit the login button twice before the page is finished submitting.
You will get a JS error of i18n_com_tle_web_sections_equella_alreadysubmitting is not defined.  This variable used to hold the string value of "The page is already being submitted"

**Expected behavior**
You get an alert or some-such that displays the text "The page is already being submitted"

**Comment by SammyIsConfused** [comment]
This seems to be working from my end, at least in the login button context.

**Comment by SammyIsConfused** [comment]
Confirmed working in 2018.2.
