### ISSUE TITLE
Can't edit custom links in OLD ui on 6.7

### ISSUE THREAD

**Issue by doolse** [equella/Equella#626]
**Describe the bug**
If you create a custom link and then go back to edit it, the title and url are reset to their defaults.

**To Reproduce**
1. Go to Settings / General / Custom links in OLD UI
2. Add new link
3. Enter some values for the title and URL and Save 
4. Edit your new link 
5. Values are reset back to blank and "http://"

**Comment by SammyIsConfused** [comment]
Confirmed working in 6.7
