### ISSUE TITLE
Adjust line spacing and text font size in new Course Selector

### ISSUE THREAD

**Issue by cathfitz** [equella/Equella#632]
Return course results in new dropdown without the line space in between each results (so more results can show without needing to scroll), and make the overall results text smaller, as some course names can be quite long. The text size is currently much bigger than everything else on the layout templates.

**Comment by edalex-ian** [comment]
![2018-12-11-095254_595x444_scrot](https://user-images.githubusercontent.com/43919233/49766900-b90eaa80-fd2a-11e8-954c-e69372591582.png)

**Comment by mrblippy** [comment]
Verified in 2018.2
