### ISSUE TITLE
Course editor minor problems

### ISSUE THREAD

**Issue by doolse** [equella/Equella#634]
There are a few minor issues
- [x] If you try and save the course from the permissions tab but you have an invalid field on the details tab, it doesn't switch to the tab to tell you about it
- [x] The expected audience field should default to 0
- [x] The "speed dial" for adding new expression term types on the permissions page isn't working

**Platform:**
 - OpenEquella 6.7

**Comment by SammyIsConfused** [comment]
The expected audience field still has some issues. If you put a non-number string into it, the hint string shows up behind the string.
![image](https://user-images.githubusercontent.com/24543345/49839743-8507b800-fe04-11e8-9562-309b3c626d15.png)

**Comment by SammyIsConfused** [comment]
Confirmed working on Firefox and Chrome.
