### ISSUE TITLE
Part of openEQUELLA logo getting cut off inside selection session

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#636]
**Screenshots**
![cropped](https://user-images.githubusercontent.com/4625498/49488646-9a786180-f89b-11e8-9888-8717d73b9c9d.PNG)

**Platform:**
 - OpenEquella Version: 2018.2
 - OS: Windows 10
 - Browser Chrome

**Comment by edalex-ian** [comment]
I think you've already got the fix for this @doolse ?

**Comment by mrblippy** [comment]
Verified in 2018.2
