### ISSUE TITLE
Turning off New UI doesn't work until manual refresh

### ISSUE THREAD

**Issue by edalex-ian** [equella/Equella#639]
**Describe the bug**

There is a regression in 2018.2 beta where if you turn off the New UI it has no effect until you go to a page other than settings, and press F5 (browser refresh).

In 6.6 Stable, after changing the setting I could click on 'Dashboard' and the New UI would be turned off.

**To Reproduce**

Steps to reproduce the behaviour (assuming you're on a server which already has the new UI enabled):
1. Go to Settings > UI 
2. Click the toggle for 'Enable new UI' so that it is *off*
3. Click on the 'Dashboard' menu item - observe that you're still in the new UI
4. Press F5 to refresh your browser - observe that now you in the old UI

**Expected behaviour**

When I arrive at the dashboard in step 3 above I expect to see the system in the old UI.

**Platform:**

 - OpenEquella Version: 2018.2-beta
 - OS: Ubuntu server, Debian client
 - Browser Firefox

**Additional context**

I've confirmed this works in 6.6-Stable.

**Comment by SammyIsConfused** [comment]
Issue no longer relevant, as the "Enable new UI" switch now reloads the page and changes the UI instantly.
