### ISSUE TITLE
'Edit Theme Settings' button fails to work immediately after enabling new UI

### ISSUE THREAD

**Issue by edalex-ian** [equella/Equella#641]
**Describe the bug**

Clicking the 'Edit Theme Settings' button has no effect until the New UI has been triggered. Unfortunately, although the toggle to enable the New UI shows this button, the New UI is only triggered once you go to another page.

(So you have to enable the new UI, go to another page, then come back and click the button.)

**To Reproduce**

Steps to reproduce the behaviour (assuming a server which does *not* have the new UI enabled):

1. Go to Settings > UI
2. Turn on the 'Enable new UI'
3. Click the 'Edit Theme Settings'
4. **ERROR** Other than the ripple animation on the button, nothing happens - you can click it again and again.
5. Click on 'Dashboard' - triggers new UI
6. Go back to Settings > UI
7. Clicking the button now works.

Or an interesting variation  (assuming a server which does *not* have the new UI enabled):

1. Go to Settings > UI
2. Turn on the 'Enable new UI'
3. Click the 'Edit Theme Settings'
4. Noting that nothing happens, press F5.
5. You find yourslelf in the new UI and suddenly on the Theme Settings page.

**Expected behaviour**

Seeing switching the toggle for 'Enable new UI' shows the 'Edit Theme Settings' button, I expect I can click it and start changing theme settings.

Indeed, considering there's no 'apply' or 'save' buttons, clicking the toggle for 'Enable new UI' I'd expect to immediately change to the new UI (maybe with a confirmation dialog). Perhaps if that was in place, then this would be a non-issue.

**Platform:**
 - OpenEquella Version: 2018.2 beta
 - OS: ubuntu (server), debian (client)
 - Browser: Firefox

**Comment by edalex-ian** [comment]
@doolse is there a reason that toggling the 'Enable new UI' doesn't have immediate effect (possibly after confirmation dialog)?

**Comment by SammyIsConfused** [comment]
Issue no longer relevant, as the "Enable new UI" switch now reloads the page and changes the UI instantly. Pressing the "Edit Theme Settings" button is now only possible from the new UI, since it is disabled in the old UI.
