### ISSUE TITLE
Item breadcrumbs lead back to old UI, even when new ui is enabled

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#649]
**Describe the bug**
At the top of every item summary page there is a breadcrumb that takes you to a search page that only displays items from a specific collection.

When the new search page is enabled this breadcrumb still goes to the old search page (searching.do), eg. http://charlielap:8021/vanilla/searching.do?in=C241dfa27-5023-4b89-91ca-1f716cb2cf9b&sq_currentHidden=C241dfa27-5023-4b89-91ca-1f716cb2cf9b&q=&type=standard&sort=rank&dr=AFTER&page=1

Seems like it would be confusing to users, it confused me. It's probably because the new search page can't yet handle the parameters in the query string above.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable the new search page (Settings -> UI)
2. Perform a search
3. Click on one of the results
4. On the item summary page, click the breadcrumb link
5. Notice that it's going to the old search page

**Expected behavior**
Should go to the new search page

**Screenshots**
![capture](https://user-images.githubusercontent.com/4625498/49840524-debdb180-fe07-11e8-82a5-9e738aab3af3.PNG)

**Platform:**
 - OpenEquella Version: 6.6, 2018.2
 - OS: Windows 10
 - Browser Chrome

**Comment by edalex-ian** [comment]
Due to time and that it was in 6.6, scheduling for 2019.1.

**Comment by edalex-ian** [comment]
@mrblippy has tested ready for closing.
