### ISSUE TITLE
Change ITunesU web control

### ISSUE THREAD

**Issue by doolse** [equella/Equella#65]
We currently use a [library](https://code.google.com/archive/p/itunesu-api-java/) which we use that is just a simple wrapper around the ITunesU web service, but it's not on a maven repository. So we have a few choices:

* Publish it ourselves - it's BSD 3 does this allow us to?
* Rewrite the code to not need the library, it's only a simple wrapper, so wouldn't be the end of the world.

The web control is in the "com.tle.web.wizard.controls.itunesu" plugin.

**Comment by cbeach47** [comment]
@drewwills - do you agree that the BSD 3 license allows us to publish the iTunesU web service ourselves?  I don't see why not.

Since there are a few dependencies we are looking to publish, I'm leaning towards @doolse 's option #1.

**Comment by cbeach47** [comment]
Drew confirmed BSD3 looks fine.

Blocked by #36 to publish our own version.

**Comment by doolse** [comment]
Will be handled in #79
