### ISSUE TITLE
New UI Theme Configuration cosmetic tweaks

### ISSUE THREAD

**Issue by edalex-ian** [equella/Equella#653]
A review by @cathfitz and subsequent discussion has resulted in the following requested tweaks to the New UI Theme Configuration:

- [x] Reword the 'Revert Changes' button to 'Undo'
- [x] 'Reset to Default' button should auto-apply
- [x] Change the two secondary buttons to have same style (go with outline for both me thinks)

**Platform:**

 - OpenEquella Version: 2018.2r104

**Comment by SammyIsConfused** [comment]
#655

**Comment by mrblippy** [comment]
Should the undo button be clickable when there is nothing to undo?

**Comment by SammyIsConfused** [comment]
> Should the undo button be clickable when there is nothing to undo?

Shouldn't really matter. I could add a method to check whether it is the same as the default with every colour change and enable the button accordingly but I doubt it really matters enough to do that.

**Comment by mrblippy** [comment]
Verified in 2018.2
