### ISSUE TITLE
Currently supported version of LibAV

### ISSUE THREAD

**Issue by goetzk** [equella/Equella#676]
Hi,
I'm wondering what version/s of LibAV oE is tested against at the moment. The documentation refers to 11.3 which is old old old so it would be good to have a definite idea about what is supported.

The only clue I see is libav-tools mentioned in a travis configuration file under the equella-autotests repository - but that is 9.20 so even older than the current documentation.
https://packages.ubuntu.com/trusty/libav-tools

karl

**Comment by edalex-ian** [comment]
Heya @goetzk 

On our Debian test servers we're currently running:

    libav-tools/now 7:3.2.12-1~deb9u1

Heya @mrblippy 

Do you have any comments on this - especially what's used with Windows?

**Comment by mrblippy** [comment]
I just tested with the latest windows libav build from http://builds.libav.org/windows/nightly-gpl/
It's not exactly recent though, the latest build is from 08/01/2018.

Video previewing and thumbnailing is working correctly in oEQ with that version

**Comment by edalex-ian** [comment]
Further to my comment above, we've also had a bit of a look at the transitional package that Debian are offering. And it seems that the ffmpeg package and tools are CLI compatible. So simple symlinking is an option - and needed on newer platforms.

Ultimately though, we need to update so we're no longer dependent on something which is deprecated. I'll raise a ticket.

**Comment by edalex-ian** [comment]
Closing due to action items to address actual code and documentation.
