### ISSUE TITLE
Z3950 library changes / investigation

### ISSUE THREAD

**Issue by doolse** [equella/Equella#68]
We use the Jafer z39.50 toolkit library for searching library systems with the Z3950 protocol and it doesn't appear to be on Maven.  https://www.openhub.net/p/jafer

So we need see if we can track it down on some open repository or worse case publish our own version of it.

**Comment by cbeach47** [comment]
@doolse - I haven't been able to find an open repository with this library.  I think we'll need to publish our own version.  Please let me know if you disagree.

Blocked by #36 to publish our own version.

**Comment by doolse** [comment]
Will be handled by #79
