### ISSUE TITLE
SOAP "fastSearch" fails with exception

### ISSUE THREAD

**Issue by doolse** [equella/Equella#680]
**Describe the bug**
Using the Soap51 endpoint method "searchItemsFast" fails with 

`org.apache.cxf.binding.soap.SoapFault: an implementation is missing`

**To Reproduce**
1. Run the Autotest `Soap51Test`

**Platform:**
 - OpenEquella Version: 2018.2

**Comment by SammyIsConfused** [comment]
Tested on 6.6-stable, 2018.2-stable and 2019.1-alpha. Soap51Test checks out.
