### ISSUE TITLE
Redirect URLs generated for parameters which can have multiple values only return first value

### ISSUE THREAD

**Issue by doolse** [equella/Equella#682]
**Describe the bug**
openEQUELLA uses [Post/Redirect/Get](https://en.wikipedia.org/wiki/Post/Redirect/Get) for most browser interactions. The Redirect URL is currently only generating a parameter for the first value of a multi valued parameter. This manifests itself as problems with some multi selection lists such as:
* Selecting multiple attachments to activate using CAL
* Selecting mutiple values from report parameters

**To Reproduce**
Run one of these test methods
1. `CALBookActivationTest - testActivateMultiple`
2. `RunReportTest - runDisplayTextParametersTest`

**Platform:**
 - OpenEquella Version: 2018.2

**Comment by SammyIsConfused** [comment]
Tested on 2018.2-Stable and 2019.1-Alpha. Autotests check out.
