### ISSUE TITLE
Uploading files into TinyMCE editor fails

### ISSUE THREAD

**Issue by doolse** [equella/Equella#684]
**Describe the bug**
The TinyMCE editor allows you to upload a file and create a link to it but it currently fails with an exception.

**To Reproduce**
1. Run `MyResourcesWebPageTest - uploadAttachmentToWebPageTest`

OR

2. Author new scrapbook web page
3. Click the attach file icon (little paper clip)
4. BOOM

**Expected behavior**
When you select a file it should create a link to it in your editor.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/2178038/50498650-c059e600-0a96-11e9-8d1a-677c4d01626a.gif)

**Platform:**
 - OpenEquella Version: 2018.2

**Comment by SammyIsConfused** [comment]
Tested in 2018.2-stable and 2019.1-alpha. `MyResourcesWebPageTest - uploadAttachmentToWebPageTest` checks out.
