### ISSUE TITLE
Cannot edit CAL activations that are currently active

### ISSUE THREAD

**Issue by doolse** [equella/Equella#686]
**Describe the bug**
Users can edit the end date of a CAL activation which is currently active but cannot change the from date or course. This currently fails with an exception when you click save.

**To Reproduce**
1. Run `CalBookActivationTest - testEditActivation`

**Expected behavior**
It should change the end date of the activation

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/2178038/50499182-a8389580-0a9b-11e9-9dd5-e6afcbe2fa9d.gif)

**Platform:**
 - OpenEquella Version: 2018.2

**Comment by SammyIsConfused** [comment]
Tested on 2018.2-stable and 2019.1-alpha. `CalBookActivationTest - testEditActivation` checks out.
