### ISSUE TITLE
hurl URL handling library changes / investigation

### ISSUE THREAD

**Issue by doolse** [equella/Equella#69]
We picked up a library from someone's blog and used it but it doesn't appear to be on maven. 
It's possible that it isn't used extensively and we could just re-write the parts that use it.

http://illegalargumentexception.blogspot.com.au/2009/12/java-safe-character-handling-and-url.html

**Comment by cbeach47** [comment]
Based on that blog entry, the license is MIT (OK), but the code is not hosted.  I checked on Maven and did a wider search on the web.  Also, according to the blog, the author didn't plan to host it, and stated the code was not tested for production use.  However, it's been integrated with Equella for some time, and there are no current complaints against it (that I'm aware of).

While the number of places in the code are not extensive, the testing impact will take time - CAS, OAuth, External Authorization, Canvas, Auto IP, etc.

I recommend we add the hurl 1.1 dependency into an open repo.

**Comment by cbeach47** [comment]
Blocked by issue #36

**Comment by doolse** [comment]
Will be handled by #79
