### ISSUE TITLE
Login notice does not display properly on oEQ 2018.2 when new UI is enabled

### ISSUE THREAD

**Issue by nelson-edalex** [equella/Equella#693]
**Describe the bug**
The login notice screen is always blank if a login notice is configured on oEQ 2018.2 **if new UI is enabled**.

**To Reproduce**
1. Upgrade to oEQ 2018.2
2. Login as admin and configure a login notice in Settings > Login
3. Enable new UI in Settings > UI
3. Make sure you did not hide login notice in User Preference
4. Logout and login again.

**Expected behavior**
The login notice should be displayed.

**Screenshots**
N/A

**Stacktrace**
N/A

**Platform:**
 - OpenEquella Version: 2018.2
 - OS: N/A
 - Browser: Latest Chrome and Firefox

**Additional context**
N/A

**Comment by mrblippy** [comment]
Verified in 2018.2
