### ISSUE TITLE
File API rename folder errors out

### ISSUE THREAD

**Issue by doolse** [equella/Equella#696]
**Describe the bug**
The /file API has a PUT method which renames a folder by passing in the filename inside a JSON object. Currently it errors with a Jackson deserialisation exception. 

**To Reproduce**
1. Run `FileApiTest - testEverything`

**Platform:**
 - OpenEquella Version: 2018.2

**Comment by edalex-ian** [comment]
Hey @doolse 

Is this done with #698 ?

**Comment by doolse** [comment]
Yep, oops missed out the ref in the description

**Comment by SammyIsConfused** [comment]
Tested on 2019.1. You're good to backport this.

**Comment by edalex-ian** [comment]
Probably a bit late to backport now, and it's been tested, so let's close.
