### ISSUE TITLE
Apply license headers to all sources

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#7]
Use a build plug in

**Comment by emcgarrahan** [comment]
Research Gradle options

**Comment by bjagg** [comment]
Found several Gradle plugins related to this. Will be working through them next.

**Comment by drewwills** [comment]
Somehow I took @bjagg off this ticket, but I didn't mean to.

**Comment by bjagg** [comment]
Jolse looking into this

**Comment by bjagg** [comment]
FYI, license maven plugin used my uPortal and all the portlets
<groupId>com.mycila</groupId>
<artifactId>license-maven-plugin</artifactId>

**Comment by bjagg** [comment]
Awaiting SBT tooling

**Comment by bjagg** [comment]
@doolse You mentioned this was resolved with SBT. Can we close this or is there more work to do?

**Comment by doolse** [comment]
The license header has been applied.
