### ISSUE TITLE
qtiworks jqtiplus library changes / investigation

### ISSUE THREAD

**Issue by doolse** [equella/Equella#70]
We have a QTI quiz player in EQUELLA which uses an open source library which wasn't found on Maven central. We need to either track it down somewhere else or publish it ourselves.

https://github.com/davemckain/qtiworks

**Comment by cbeach47** [comment]
Doesn't look like there is a hosted binary of qtiworks yet.  According to the github [install directions](https://github.com/davemckain/qtiworks/wiki/QTIWorks-Engine-installation-guide), they'll cut official binaries when 1.0 is officially released, but for now, the latest (7Apr2017) release is 1.0.0beta10.

Looks like this is another dependency that we have to make public ourselves.

**Comment by cbeach47** [comment]
Blocked by #36

**Comment by doolse** [comment]
Will be handled by #79
