### ISSUE TITLE
Store IntelliJ IDEA Project Settings

### ISSUE THREAD

**Issue by edalex-ian** [equella/Equella#709]
We want to store the IntelliJ project settings in the repo, primarily to lever full code style settings, but also aid with other developers starting up fresh.

So we need to add the `.idea` folder, however we should make sure out `.gitignore` has:

```
### Intellij ###
## https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

.idea/artifacts/
.idea/httpRequests/

# User-specific stuff:
.idea/workspace.xml
.idea/tasks.xml
.idea/dictionaries
.idea/vcs.xml
.idea/jsLibraryMappings.xml

# Sensitive or high-churn files:
.idea/dataSources.ids
.idea/dataSources.xml
.idea/dataSources.local.xml
.idea/dataSources/
.idea/sqlDataSources.xml
.idea/dynamic.xml
.idea/uiDesigner.xml

## And seeing SBT projects also regenerates .iml module files
## lets ignore them all:
.idea/modules/

### Intellij - END ###
```

We can start there, and see how we go.

But key is to make sure we include the `codeStyles/` folder.

**Comment by ChristianMurphy** [comment]
Just a thought, rather than commiting the intellij files, locking contributors into a specific config.
Maybe offer a way to generate the .idea folder if wanted, while still allowing customization.
Something like: https://github.com/mpeltonen/sbt-idea

**Comment by edalex-ian** [comment]
I think this can now be closed.
