### ISSUE TITLE
Allow to configure the now hardcoded support@equella.com email address

### ISSUE THREAD

**Issue by ddelblanco** [equella/Equella#71]
support@equella.com email address is hardcoded at 

com/tle/common/externaltools/constants/ExternalToolConstants.java:42

and used as LTI parameter. This should be able to be configured by the institution.

**Comment by ddelblanco** [comment]
I'll leave this as a lower priority one and I will work in the libraries ones before continue, so if someone wants to pick this one, it is open.

**Comment by cbeach47** [comment]
Changes complete.  Pull request #97 opened.

**Comment by cbeach47** [comment]
Changes merged.
