### ISSUE TITLE
Institution import language strings not set

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#73]
Found when building from source on 5/18.
- Build installer via sbt
- Install via gui
- bring up server admin pages
- Access the import institution launch page - there's a bunch of displayed strings like ???institutions.import.action.name???

**Comment by cbeach47** [comment]
@ddelblanco - can you replicate?

**Comment by doolse** [comment]
It's due to the same problem as the null pointer in the installer, it was only working after compiling in intellij cos it treats resources in source folders differently, it should be fixed now, can you try with the latest?

**Comment by cbeach47** [comment]
That did the trick, thanks @doolse
