### ISSUE TITLE
when I try to install with in windows 10 , postgre sql 10, after giving username and password

### ISSUE THREAD

**Issue by rahimansar** [equella/Equella#742]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**
 - OpenEquella Version: [e.g. 6.5, 6.6]
 - OS: [e.g. Windows 10, MacOS 10.13]
 - Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by rahimansar** [comment]
![image](https://user-images.githubusercontent.com/11922619/52260781-9bcc1600-2940-11e9-95c5-b012ff5de62e.png)

**Comment by edalex-ian** [comment]
Sorry @rahimansar we'll need some more information than that. Could I please request you go back and complete that template describing the details of your issue and maybe what you've done.

I see it's failed to connect to your DB, but how you got there would be good.

But in the meantime, make sure that you've provided the correct username and password for your database. And I assume you have created the database and confirmed your PostgreSQL is working correctly. (If not, please check - and perhaps connect with the credentials you're trying to use - with perhaps pgAdmin.)

**Comment by rahimansar** [comment]
Many thanks for the reply . As per the document I created a new super db user equellauser and created database equella.  When I tried to install equella using this installer equella-installer-2018.2  . For database authentication it is giving only option for the username, database name and no option for password. So tried creating a user with blank password it also didn't work. Postgre DB is running and i created new user and new DB.
![image](https://user-images.githubusercontent.com/11922619/52265620-f61fa380-294d-11e9-9756-f73363698bbb.png)

**Comment by rahimansar** [comment]
![image](https://user-images.githubusercontent.com/11922619/52265830-5adafe00-294e-11e9-8242-3af267563f27.png)

**Comment by cbeach47** [comment]
Hi @rahimansar , 

Like @edalex-ian noted, some more details would be helpful.  Some thoughts:

Just confirmed on Ubuntu and Windows 10 that the DB password field shows up for the Installer.  

You can also install in headless mode.  open a prompt and run `java -jar location/of/enterprise-install.jar --unsupported defaults.xml` where an example defaults.xml is found in https://github.com/equella/Equella/blob/develop/docker/defaults.xml  .

Might try installing in a different OS, and see if your installer has the same problem.

Where did you get the installer from?

Cheers,
Chris

**Comment by edalex-ian** [comment]
Based on extended in-activity, closing for now. Can re-open if further assistance required.
