### ISSUE TITLE
Missing I18N strings for Attachment save confirmation dialog

### ISSUE THREAD

**Issue by edalex-joe** [equella/Equella#747]
**Describe the bug**
Internationalization strings are missing in the Admin Console for a particular confirmation message that appears when saving an Attachment control without specifying any attachment types (Files, Google Books etc). This is when adding items to a collection definition.

**To Reproduce**
1. Go to the Collection Definition editor and navigate to the Wizard tab
2. Add a new Attachments control to a page
3. Enter the Title and Metadata target for the control and click Save.
4. See error screenshot below for message keys

**Expected behavior**
Valid English strings should replace the I18N placeholders.

**Platform:**
 - OpenEquella Version: 2019.1-R35

![screenshot from 2019-02-13 11-53-48](https://user-images.githubusercontent.com/47160744/52681614-897d5800-2f90-11e9-9aac-1783a8a2c2a5.png)

**Comment by mrblippy** [comment]
Verified in 2019.1

**Comment by edalex-ian** [comment]
I think commit messages may have got a bit confused, but I believe this was also backported. Have you had a chance to verify on 2018.2?

**Comment by mrblippy** [comment]
Also verified in 2018.2
