### ISSUE TITLE
METS from edu.harvard.hul has undefined license

### ISSUE THREAD

**Issue by bjagg** [equella/Equella#78]
To resolve this, we should investigate if this functionality is still needed (METS support). If not, remove due to confusion on license. (One page lists this dependency as LGPL.) If used, we should replace with one of the following:

An alternative is https://sourceforge.net/projects/mets-api/ which is under Apache2 license, and http://sourceforge.net/projects/seventrain which is under BSD.

**Comment by cbeach47** [comment]
Working to pull this code into it's own repo.  I checked with @doolse who didn't conceptually see any major issues, and I've sent a follow up note to a few folks to confirm user stories.

**Comment by cbeach47** [comment]
Code changes and smoke tests complete.  Test binaries with and without METS are built.  Requested some advice on a more complete test suite for METS.  Plan to run the tests using the binaries tomorrow.

We will have to put the hul mets external dep into Maven local for now, and then publish ourselves.

@drewwills - please create an Equella-METS repo similar to #55 .

**Comment by cbeach47** [comment]
METS code published as an 'optional functionality' here:  https://github.com/equella/Equella-METS

**Comment by doolse** [comment]
I've used the way back machine to find the original license - it's LGPL, which means we can publish it yeah?

https://web.archive.org/web/20100413195423/http://hul.harvard.edu:80/mets/download.html

**Comment by cbeach47** [comment]
Confirmed with @drewwills and @bjagg yesterday - LGPL is valid to publish the dependency for Equella in the core base.

**Comment by cbeach47** [comment]
- Removed the 'optional functionality' and 'migration testing' documentation.
- Closed the pull request #91 and deleted the issues/78 branch
- Added this dependency into #79
@drewwills - please remove the Equella-METS repo.  Then we can close this issue.

**Comment by drewwills** [comment]
- [ ] Done
