### ISSUE TITLE
Failing to edit an item as a moderator

### ISSUE THREAD

**Issue by PenghaiZhang** [equella/Equella#781]
**Describe the bug**
This bug only occurs in new UI.
Moderators cannot edit an item when they are moderating

**To Reproduce**

To test the second bug,

1. Login in as a moderator,
2. Select a task to moderate,
3. Click Edit resource button,

Expected behavior
An error message pops up.

**Screenshots**
![Screenshot from 2019-03-15 16-35-02](https://user-images.githubusercontent.com/47203811/54411760-51f6fc80-4744-11e9-956c-efdc1ff40b3a.png)

**Platform:**

OpenEquella Version: 6.6, 2018.2
OS: Ubuntu
Browser Chrome

**Comment by edalex-ian** [comment]
There is no strict requirement for this to be backported, and seeing the fix in 2019.1 was in an area of the Purescript that has been significant reworked it would require undue to prepare a different fix.

But it's all tested in `develop`, so closing now.
