### ISSUE TITLE
Enhance AttachmentScriptType api to accept more primitive types as customProperties

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#786]
**Is your feature request related to a problem? Please describe.**
From Nelson 
"The custom properties qti_fileSize and qtr_maxTime are Long but in the scripting API, I only have:
setCustomProperty() - this saves the value as String or Double
setCustomIntegerProperty() - this saves the value as Integer
In either case, EQUELLA complains with a type cast error in item summary page."

Currently the scripting api (AttachmentScriptType in particular) has methods to set properties for custom attachments:
- `setCustomProperty(java.lang.String propertyName, java.lang.Object propertyValue) `

- `setCustomIntegerProperty(java.lang.String propertyName, int propertyValue)`

neither of them allow for the user to explicitly set a long or double.

**Describe the solution you'd like**
Since there is already a setCustomIntegerProperty method, we could just add setCustomLongProperty and setCustomDoubleProperty methods. It's probably best to not modify the existing methods, in case it causes existing scripts to behave differently

**Comment by edalex-ian** [comment]
All done and released.
