### ISSUE TITLE
Publish open source libraries to maven with our group id

### ISSUE THREAD

**Issue by doolse** [equella/Equella#79]
The following libraries have licenses which will allow us to publish our own binaries
- [ ] reporting-common 6.3
- [ ] reporting-oda 6.3
- [ ] reporting-oda-connectors 6.3
- [ ] uk.ac.ed.ph.qtiworks - qtiworks-jqtiplus
- [ ] org.jafer - z3950
- [ ] org.jafer.zebulun:1.0 ( LGPL v3)
- [ ] org.oclc.oai.oaicat:1.5.57 ( Apache )
- [ ] org.onemind.jxp.jxp:1.2.0 ( LGPL )
- [ ] org.hurl - hurl
- [ ] jpf - jpf  ( LGPL , modified source )
- [ ] jpf - jpf tools 1.0.5 ( LGPL , modified source )
- [ ] org.eclipse.birt - (birt-api, birt-osgi, org.eclipse.birt.api)
- [ ] edu.asu.itunesu - itunesu-api-java
- [ ] edu.harvard.hul - mets

**Comment by cbeach47** [comment]
As per #78, METS should also be publish with this group.  I've updated the initial comment / description of this issue.

**Comment by cbeach47** [comment]
Updated the descriptive comment with:
- [ ] org.jafer.zebulun:1.0 ( LGPL v3)
- [ ] org.oclc.oai.oaicat:1.5.57 ( Apache )
- [ ] org.onemind.jxp.jxp:1.2.0 ( LGPL )
- [ ] jpf - jpf tool 1.0.5 ( LGPL , modified source )

**Comment by cbeach47** [comment]
Added the rest of what needs to go into the local maven repo from #95.

**Comment by doolse** [comment]
All deps are now on maven central
