### ISSUE TITLE
The New UI Theme Editor is only setting the secondary text colour, not the primary

### ISSUE THREAD

**Issue by edalex-ian** [equella/Equella#797]
**Describe the bug**

Currently the New UI theme editor only provides on setting for text colours: 'Text Colour'. Unfortunately, it turns out this is currently controlling the secondary colours for Material UI.

![Screenshot_2019-03-27 Theme Settings openEQUELLA](https://user-images.githubusercontent.com/43919233/55045448-eab94080-5091-11e9-8ed4-2643f80e36df.png)

**Expected behavior**

If we only have one control that should do the primary colour. However, it would be better to see this fixed with an additional control - i.e. one for primary and one for secondary.

**Platform:**

- OpenEquella Version: 2019.1 maybe 2018.2

**Additional context**

Not sure if this in 2018.2, as there's a chance it's come about only in our 2019.1 work while updating Material UI. Either way, we need to fix.

**Comment by mrblippy** [comment]
Verified in 2019.1
