### ISSUE TITLE
Obtain ICLAs and Corporate CLA from Edalex

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#8]

**Comment by drewwills** [comment]
Edalex folks -- what's the status of this item?

**Comment by doolse** [comment]
I'm registered with Apereo, so has @mrblippy (Nick Charles). Not sure about @abidingotter (Aaron Holland) and Alistair Oliver submitted the Corporate CLA yesterday.

**Comment by drewwills** [comment]
I invited @mrblippy to the repo.

**Comment by abidingotter** [comment]
I signed my CLA yesterday, but no response from Apereo yet.  Will keep you updated.

**Comment by drewwills** [comment]
Great -- I added @abidingotter.

Is there anyone else we're waiting on?

**Comment by drewwills** [comment]
@doolse -- If we're done with ICLAs and adding folks to this repo, please resolve the ticket.

**Comment by doolse** [comment]
Still waiting to get a response back from Apereo for our Corporate CLA

**Comment by drewwills** [comment]
I can see Edalex still isn't on the list here...

  - http://licensing.apereo.org/

I'll email someone at Apereo right now.

**Comment by drewwills** [comment]
From Ian at Apereo...

    We have the agreement, but didn’t want to list it until the Equella deal was made public.
