### ISSUE TITLE
Re-implement file upload features

### ISSUE THREAD

**Issue by doolse** [equella/Equella#84]
In #80 the code was fixed to not require the special commons upload jar, which is working but it now lacks a couple of features which we need to be re-implemented, most likely in javascript.

* File upload progress bars
* Fast failure for invalid uploads (invalid mime type)

Also the multipart parsing is now handled by tomcat which has some maximum sizes which need configuring somewhere.

**Comment by cbeach47** [comment]
@doolse - do you have a good understanding of what will need to change and/or do you think this is something you can tackle early next week?

**Comment by doolse** [comment]
Yeah i'll have a crack at it
