### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by RobbieCoombs** [equella/Equella#92]
Hi team,

Are the following errors indicative of the dependencies which are contained in the equalla-dep.zip file?  Not sure if the Equella bitbucket storage for the .zip is intentionally private, but I can't access it to find out on my own.

[error] (org_eclipse_birt_osgi/*:update) sbt.ResolveException: unresolved dependency: org.eclipse.birt#birt-osgi;3.7.2: not found
[error] unresolved dependency: com.tle.reporting#reporting-common-6.3;0.20141006: not found
[error] unresolved dependency: com.tle.reporting#reporting-oda-6.3;0.20141006: not found
[error] unresolved dependency: com.tle.reporting#reporting-oda-connectors-6.3;0.20141006: not found
[error] unresolved dependency: org.eclipse.birt#org.eclipse.birt.api;1: not found
[error] (com_tle_common_remoterepo_z3950/*:update) sbt.ResolveException: unresolved dependency: org.jafer#z3950;1.1: not found
[error] (com_tle_core_reporting/*:update) sbt.ResolveException: unresolved dependency: org.eclipse.birt#birt-api;3.7.2: not found
[error] unresolved dependency: com.tle.reporting#reporting-common-6.2;2: not found
[error] (adminConsoleJar/*:update) sbt.ResolveException: unresolved dependency: jpf#jpf;1.0.7: not found
[error] (equellaserver/*:update) sbt.ResolveException: unresolved dependency: edu.asu.itunesu#itunesu-api-java;1.7: not found
[error] unresolved dependency: edu.harvard.hul#mets;1.0: not found
[error] unresolved dependency: jnlp#jnlp;1.0: not found
[error] unresolved dependency: jpf#jpf;1.0.7: not found
[error] unresolved dependency: jpf#jpf-tools;1.0.5: not found
[error] unresolved dependency: org.hurl#hurl;1.1: not found
[error] unresolved dependency: org.oclc.oai#oaicat;1.5.57: not found
[error] unresolved dependency: uk.ac.ed.ph.qtiworks#qtiworks-jqtiplus;1.0-beta3: not found

**Comment by cbeach47** [comment]
Hi @RobbieCoombs - yes, that is due to not having the dependencies in the equella-deps folder.  We are preparing those dependencies to be available to the community and the work should be completed soon.  I've updated the installation / development setup guides to reflect this, and will update this issue when it's publicly available.

**Comment by RobbieCoombs** [comment]
No problem, thanks for getting back to me.

**Comment by cbeach47** [comment]
Hi @RobbieCoombs - the equella-deps folder has been scrubbed, and we've released a zip of the dependencies we plan to self-publish in the near future [here](https://github.com/equella/Equella/releases/tag/6.4-Beta).
